#!/usr/bin/env python3
"""
Batch-generate English zone dialogues via local Ollama API.

Reads llm-prompts.json and feeds each prompt to your local LLM.
Collects JSON outputs into a single TypeScript file.

Prerequisites:
    pip install requests
    ollama run mistral   (or your preferred model)

Usage:
    python scripts/batch-generate-ollama.py --model mistral
    python scripts/batch-generate-ollama.py --model mixtral --output src/data/zone-stories-en-batch.ts
"""

import json
import argparse
import time
from pathlib import Path

try:
    import requests
except ImportError:
    print("ERROR: requests not installed. Run: pip install requests")
    raise SystemExit(1)

PROMPTS_FILE = Path(__file__).parent.parent / "llm-prompts.json"
DEFAULT_OUTPUT = Path(__file__).parent.parent / "src" / "data" / "zone-stories-en-batch.ts"
OLLAMA_URL = "http://localhost:11434/api/generate"


def generate_one(model: str, system: str, user: str) -> dict:
    """Call Ollama API for a single conversation."""
    payload = {
        "model": model,
        "system": system,
        "prompt": user,
        "stream": False,
        "format": "json",
        "options": {
            "temperature": 0.7,
            "num_predict": 800,
        }
    }
    resp = requests.post(OLLAMA_URL, json=payload, timeout=120)
    resp.raise_for_status()
    data = resp.json()
    raw = data.get("response", "{}").strip()
    # Some models wrap JSON in markdown
    if raw.startswith("```"):
        raw = raw.strip("`").strip()
        if raw.lower().startswith("json"):
            raw = raw[4:].strip()
    return json.loads(raw)


def main():
    parser = argparse.ArgumentParser(description="Batch-generate zone dialogues via Ollama")
    parser.add_argument("--model", default="mistral", help="Ollama model name (default: mistral)")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output TS file")
    parser.add_argument("--delay", type=float, default=1.0, help="Seconds between requests")
    parser.add_argument("--limit", type=int, default=0, help="Max zones to process (0 = all)")
    args = parser.parse_args()

    if not PROMPTS_FILE.exists():
        print(f"ERROR: {PROMPTS_FILE} not found. Run prepare-llm-prompts.py first.")
        raise SystemExit(1)

    prompts = json.loads(PROMPTS_FILE.read_text(encoding="utf-8"))
    if args.limit > 0:
        prompts = prompts[:args.limit]

    print(f"Processing {len(prompts)} zones with model '{args.model}'...")
    print(f"Output will be written to: {args.output}")
    print()

    results = {}
    errors = []

    for i, p in enumerate(prompts, 1):
        zid = p["zoneId"]
        print(f"[{i}/{len(prompts)}] Generating {zid}...", end=" ", flush=True)
        try:
            result = generate_one(args.model, p["systemPrompt"], p["userPrompt"])
            results[zid] = result
            print("OK")
        except Exception as e:
            errors.append((zid, str(e)))
            print(f"FAIL: {e}")
        time.sleep(args.delay)

    # Write TypeScript output
    lines = [
        "// AUTO-GENERATED by scripts/batch-generate-ollama.py",
        "// English A1-A2 zone dialogues generated via local LLM",
        "// Review and curate before merging into zone-stories.ts",
        "",
        "export const zoneStoriesEnBatch: Record<string, any> = {",
    ]
    for zid, story in results.items():
        lines.append(f'  "{zid}_a2": {json.dumps(story, ensure_ascii=False)},')
    lines.append("};")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")

    print(f"\nDone! Wrote {len(results)} stories to {args.output}")
    if errors:
        print(f"Errors ({len(errors)}):")
        for zid, err in errors:
            print(f"  - {zid}: {err}")


if __name__ == "__main__":
    main()
