import json

# ═════════════════════════════════════════════════════════════════════════════
# NEW EN-IT LESSONS (English speakers learning Italian)
# ═════════════════════════════════════════════════════════════════════════════

new_en_it = [
  {
    "id": "en-it-articles",
    "direction": "en-it",
    "level": "a1",
    "category": "Articles",
    "title": "I am student",
    "youThink": "I am a student → Io sono studente",
    "youSay": "Io sono studente.",
    "nativeSay": "Io sono uno studente. / Io sono studente.",
    "why": "Italian often drops the indefinite article with professions after essere. But in formal contexts or when describing a role, it is used. English ALWAYS uses 'a/an' with professions.",
    "tip": "After 'sono', professions often drop the article. But 'sono uno studente' is also correct.",
    "parallels": [{"lang": "it", "text": "Sono (uno) studente."}, {"lang": "fr", "text": "Je suis étudiant."}, {"lang": "es", "text": "Soy estudiante."}],
    "examples": [
      {"correct": "Sono medico.", "wrong": "Sono un medico.", "note": "Professions after sono: drop the article."},
      {"correct": "Lui è un bravo dottore.", "wrong": "Lui è bravo dottore.", "note": "With adjectives, use the article."},
    ],
  },
  {
    "id": "en-it-gender",
    "direction": "en-it",
    "level": "a1",
    "category": "Gender",
    "title": "The car is red",
    "youThink": "The car is red → La macchina è rosso",
    "youSay": "La macchina è rosso.",
    "nativeSay": "La macchina è rossa.",
    "why": "Italian adjectives must agree in gender and number with the noun they modify. 'Macchina' is feminine, so the adjective becomes 'rossa', not 'rosso'.",
    "tip": "Every noun has gender. Adjectives follow: -o/-a/-i/-e endings.",
    "parallels": [{"lang": "it", "text": "La macchina è rossa."}, {"lang": "fr", "text": "La voiture est rouge."}, {"lang": "es", "text": "El coche es rojo."}],
    "examples": [
      {"correct": "Il tavolo è grande.", "wrong": "Il tavolo è granda.", "note": "Tavolo is masculine: grande (not granda)."},
      {"correct": "Le case sono belle.", "wrong": "Le case sono belli.", "note": "Case is feminine plural: belle (not belli)."},
    ],
  },
  {
    "id": "en-it-plurals",
    "direction": "en-it",
    "level": "a1",
    "category": "Plurals",
    "title": "One problem, two problems",
    "youThink": "Two problems → Due problemi",
    "youSay": "Due problemi.",
    "nativeSay": "Due problemi.",
    "why": "Many Italian nouns ending in -a are masculine and pluralize in -i (not -e). 'Problema' is Greek in origin, so it follows the masculine pattern: il problema, i problemi.",
    "tip": "Words ending in -ma (from Greek): il programma, il sistema, il tema → plural in -i.",
    "parallels": [{"lang": "it", "text": "Il problema → i problemi."}, {"lang": "fr", "text": "Le problème → les problèmes."}, {"lang": "es", "text": "El problema → los problemas."}],
    "examples": [
      {"correct": "I programmi sono difficili.", "wrong": "I programme sono difficili.", "note": "Programma → programmi."},
      {"correct": "I sistemi funzionano.", "wrong": "I sisteme funzionano.", "note": "Sistema → sistemi."},
    ],
  },
  {
    "id": "en-it-adj-position",
    "direction": "en-it",
    "level": "a1",
    "category": "Word Order",
    "title": "A beautiful day",
    "youThink": "A beautiful day → Una bella giornata",
    "youSay": "Una giornata bella.",
    "nativeSay": "Una bella giornata.",
    "why": "Most Italian adjectives come AFTER the noun. But common adjectives (bello, brutto, grande, piccolo, buono, cattivo, nuovo, vecchio, giovane) usually come BEFORE.",
    "tip": "BAGS adjectives (Beauty, Age, Goodness, Size) go BEFORE the noun in Italian.",
    "parallels": [{"lang": "it", "text": "Una bella giornata."}, {"lang": "fr", "text": "Une belle journée."}, {"lang": "es", "text": "Un hermoso día."}],
    "examples": [
      {"correct": "Un grande uomo.", "wrong": "Un uomo grande.", "note": "Grande before = famous/great. After = physically big."},
      {"correct": "Una casa nuova.", "wrong": "Una nuova casa.", "note": "After = brand new. Before = another house."},
    ],
  },
  {
    "id": "en-it-passato-prossimo",
    "direction": "en-it",
    "level": "a2",
    "category": "Tenses",
    "title": "I went to Rome",
    "youThink": "I went to Rome → Io andato a Roma",
    "youSay": "Io andato a Roma.",
    "nativeSay": "Sono andato a Roma.",
    "why": "Italian passato prossimo uses essere or avere as auxiliary. Movement verbs (andare, venire, partire, arrivare, entrare, uscire, tornare, salire, scendere, rimanere) take ESSERE, not AVERE. The past participle must also agree in gender.",
    "tip": "DR VAN MRS TRAMP: verbs taking essere (Dare, Rimanere, Venire, Andare, Nascere, Morire, Salire, Tornare, Ritornare, Arrivare, Entrare, Partire, Piacere...)",
    "parallels": [{"lang": "it", "text": "Sono andato a Roma."}, {"lang": "fr", "text": "Je suis allé à Rome."}, {"lang": "es", "text": "Fui a Roma."}],
    "examples": [
      {"correct": "Sono arrivata tardi.", "wrong": "Ho arrivato tardi.", "note": "Female speaker: arrivata (not arrivato)."},
      {"correct": "È morto nel 1990.", "wrong": "Ha morto nel 1990.", "note": "Morrere takes essere."},
    ],
  },
  {
    "id": "en-it-imperfetto",
    "direction": "en-it",
    "level": "a2",
    "category": "Tenses",
    "title": "I used to play football",
    "youThink": "I used to play football → Io usato giocare a calcio",
    "youSay": "Io usato giocare a calcio.",
    "nativeSay": "Giocavo a calcio.",
    "why": "Italian does not have a 'used to' construction. Instead, it uses the imperfetto tense (-avo, -evo, -ivo) for past habits, descriptions, and ongoing situations in the past.",
    "tip": "English 'used to' = Italian imperfetto. 'I used to eat' → Mangiavo.",
    "parallels": [{"lang": "it", "text": "Giocavo a calcio."}, {"lang": "fr", "text": "Je jouais au football."}, {"lang": "es", "text": "Jugaba al fútbol."}],
    "examples": [
      {"correct": "Da bambino leggevo molto.", "wrong": "Da bambino ho letto molto.", "note": "Habit in childhood: imperfetto, not passato prossimo."},
      {"correct": "Faceva freddo quel giorno.", "wrong": "Ha fatto freddo quel giorno.", "note": "Weather description in past: imperfetto."},
    ],
  },
  {
    "id": "en-it-reflexive",
    "direction": "en-it",
    "level": "a1",
    "category": "Reflexives",
    "title": "I wake up at 7",
    "youThink": "I wake up at 7 → Io sveglio alle sette",
    "youSay": "Io sveglio alle sette.",
    "nativeSay": "Mi sveglio alle sette.",
    "why": "Many everyday actions in Italian are reflexive (si + verb). 'Svegliarsi' means 'to wake oneself up.' English drops the reflexive pronoun for these verbs.",
    "tip": "Italian reflexives = English intransitives. Mi sveglio = I wake up. Mi alzo = I get up.",
    "parallels": [{"lang": "it", "text": "Mi sveglio. Mi alzo. Mi lavo. Mi vesto."}, {"lang": "fr", "text": "Je me réveille. Je me lève. Je me lave. Je m'habille."}, {"lang": "es", "text": "Me despierto. Me levanto. Me lavo. Me visto."}],
    "examples": [
      {"correct": "Mi chiamo Marco.", "wrong": "Chiamo Marco.", "note": "Mi chiamo = I call MYSELF = My name is."},
      {"correct": "Si chiama Anna.", "wrong": "Chiama Anna.", "note": "Her name is Anna (lit. She calls herself Anna)."},
    ],
  },
  {
    "id": "en-it-ci-vuole",
    "direction": "en-it",
    "level": "a2",
    "category": "Expressions",
    "title": "It takes 2 hours",
    "youThink": "It takes 2 hours → Prende due ore",
    "youSay": "Prende due ore.",
    "nativeSay": "Ci vogliono due ore.",
    "why": "Italian uses CI VUOLE / CI VOGLIONO for time/distance/effort required. Literally: 'It wants itself 2 hours.' English uses 'It takes.'",
    "tip": "Ci vuole (singular) / Ci vogliono (plural) = It takes. Never 'prende ore'.",
    "parallels": [{"lang": "it", "text": "Ci vogliono due ore."}, {"lang": "fr", "text": "Il faut deux heures."}, {"lang": "es", "text": "Se necesitan dos horas."}],
    "examples": [
      {"correct": "Ci vuole un'ora in macchina.", "wrong": "Prende un'ora in macchina.", "note": "Ci vuole = it takes (time)."},
      {"correct": "Ci vogliono tre uova.", "wrong": "Prende tre uova.", "note": "Ci vogliono = it takes (ingredients/items)."},
    ],
  },
  {
    "id": "en-it-preposition-a",
    "direction": "en-it",
    "level": "a1",
    "category": "Prepositions",
    "title": "I go TO school",
    "youThink": "I go to school → Vado a scuola",
    "youSay": "Vado in scuola.",
    "nativeSay": "Vado a scuola.",
    "why": "Italian uses A (not IN) for going to cities, small islands, and certain places like scuola, casa, teatro, cinema, letto. IN is used for countries, regions, and large islands.",
    "tip": "Andare A: cities, scuola, casa, teatro, cinema, letto. Andare IN: countries, regions, large islands.",
    "parallels": [{"lang": "it", "text": "Vado a scuola. Vado in Italia."}, {"lang": "fr", "text": "Je vais à l'école. Je vais en Italie."}, {"lang": "es", "text": "Voy a la escuela. Voy a Italia."}],
    "examples": [
      {"correct": "Vado a Roma.", "wrong": "Vado in Roma.", "note": "Cities take A."},
      {"correct": "Vado in Francia.", "wrong": "Vado a Francia.", "note": "Countries take IN."},
    ],
  },
  {
    "id": "en-it-formality",
    "direction": "en-it",
    "level": "a1",
    "category": "Formality",
    "title": "Are YOU Italian?",
    "youThink": "Are you Italian? → Sei italiano?",
    "youSay": "Sei italiano? (to a 70-year-old stranger)",
    "nativeSay": "È italiano? / Lei è italiano?",
    "why": "Italian has two forms of 'you': TU (informal, friends, family, children) and LEI (formal, strangers, elders, professionals). English uses 'you' for everyone. Using TU with a stranger is rude.",
    "tip": "When in doubt, start with Lei. The other person may say 'Diamoci del tu' (Let's use tu).",
    "parallels": [{"lang": "it", "text": "Tu sei italiano? / Lei è italiano?"}, {"lang": "fr", "text": "Tu es italien? / Vous êtes italien?"}, {"lang": "es", "text": "¿Eres italiano? / ¿Es italiano?"}],
    "examples": [
      {"correct": "Come si chiama?", "wrong": "Come ti chiami? (to a doctor)", "note": "Professionals: use Lei (si, not ti)."},
      {"correct": "Lei ha ragione.", "wrong": "Hai ragione. (to an elderly person)", "note": "Elders: always Lei."},
    ],
  },
  {
    "id": "en-it-double-negative",
    "direction": "en-it",
    "level": "a1",
    "category": "Negation",
    "title": "I don't see ANYONE",
    "youThink": "I don't see anyone → Non vedo nessuno",
    "youSay": "Non vedo qualcuno.",
    "nativeSay": "Non vedo nessuno.",
    "why": "Italian uses DOUBLE negatives: NON + negative word (nessuno, niente, mai, più). English uses 'not...anyone/anything/ever.' 'Non vedo nessuno' literally means 'I don't see no one' — grammatically correct in Italian, wrong in English.",
    "tip": "Italian: NON + nessuno/niente/mai/più. English: NOT + anyone/anything/ever/anymore.",
    "parallels": [{"lang": "it", "text": "Non vedo nessuno. Non ho niente. Non viene mai."}, {"lang": "fr", "text": "Je ne vois personne. Je n'ai rien."}, {"lang": "es", "text": "No veo a nadie. No tengo nada."}],
    "examples": [
      {"correct": "Non ho niente da fare.", "wrong": "Non ho qualcosa da fare.", "note": "Nothing = niente (not qualcosa)."},
      {"correct": "Non viene mai.", "wrong": "Non viene sempre.", "note": "Never = mai. Always = sempre."},
    ],
  },
  {
    "id": "en-it-subjunctive",
    "direction": "en-it",
    "level": "b1",
    "category": "Mood",
    "title": "I want you to come",
    "youThink": "I want you to come → Voglio che tu vieni",
    "youSay": "Voglio che tu vieni.",
    "nativeSay": "Voglio che tu venga.",
    "why": "Italian uses the subjunctive (congiuntivo) after expressions of doubt, desire, emotion, and uncertainty. 'Voglio che' triggers the subjunctive. English uses the infinitive: 'I want you TO come.'",
    "tip": "Che + subjunctive: Voglio che, Penso che, Spero che, È importante che...",
    "parallels": [{"lang": "it", "text": "Voglio che tu venga."}, {"lang": "fr", "text": "Je veux que tu viennes."}, {"lang": "es", "text": "Quiero que vengas."}],
    "examples": [
      {"correct": "Penso che sia giusto.", "wrong": "Penso che è giusto.", "note": "Penso che + congiuntivo (sia, not è)."},
      {"correct": "È importante che tu studi.", "wrong": "È importante che tu studiare.", "note": "Studi (subjunctive), not studiare (infinitive)."},
    ],
  },
  {
    "id": "en-it-false-friend-actual",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "The actual problem",
    "youThink": "The actual problem → Il problema attuale",
    "youSay": "Il problema attuale.",
    "nativeSay": "Il problema reale / vero.",
    "why": "'Attuale' in Italian means CURRENT/PRESENT, not ACTUAL. 'Attualmente' means CURRENTLY, not ACTUALLY. 'Actual' in English = reale/vero/effettivo. 'Attuale' in Italian = current/of the moment.",
    "tip": "Attuale = current. Attualmente = currently. Actual = reale/vero.",
    "parallels": [{"lang": "it", "text": "Il problema attuale = the current problem."}, {"lang": "fr", "text": "Le problème actuel = the current problem."}, {"lang": "es", "text": "El problema actual = the current problem."}],
    "examples": [
      {"correct": "L'attuale presidente.", "wrong": "Il presidente attuale (meaning actual/real).", "note": "Attuale = current."},
      {"correct": "In realtà, ho finito.", "wrong": "Attualmente, ho finito.", "note": "Actually = in realtà. Currently = attualmente."},
    ],
  },
  {
    "id": "en-it-false-friend-eventual",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "The eventual result",
    "youThink": "The eventual result → Il risultato eventuale",
    "youSay": "Il risultato eventuale.",
    "nativeSay": "Il risultato finale.",
    "why": "'Eventuale' in Italian means POSSIBLE/POTENTIAL, not EVENTUAL (which means final/ultimate after a long time). 'Eventualmente' means PERHAPS/IF NECESSARY, not eventually.",
    "tip": "Eventuale = possible. Eventualmente = perhaps/if need be. Eventually = alla fine/finalmente.",
    "parallels": [{"lang": "it", "text": "Un eventuale problema = a possible problem."}, {"lang": "fr", "text": "Un éventuel problème = a possible problem."}, {"lang": "es", "text": "Un eventual problema = a possible problem."}],
    "examples": [
      {"correct": "Eventualmente possiamo cambiare.", "wrong": "Eventually possiamo cambiare.", "note": "Eventualmente = if need be."},
      {"correct": "Alla fine ha vinto.", "wrong": "Eventualmente ha vinto.", "note": "Eventually = alla fine/finalmente."},
    ],
  },
  {
    "id": "en-it-sapere-conoscere",
    "direction": "en-it",
    "level": "a1",
    "category": "Verbs",
    "title": "I know Rome",
    "youThink": "I know Rome → So Roma",
    "youSay": "So Roma.",
    "nativeSay": "Conosco Roma.",
    "why": "Italian distinguishes between SAPERE (to know facts, information, how to do something) and CONOSCERE (to know people, places, things familiarly). English uses KNOW for both.",
    "tip": "Sapere = know THAT / know HOW. Conoscere = know PERSON/PLACE/THING.",
    "parallels": [{"lang": "it", "text": "So che è vero. Conosco Roma."}, {"lang": "fr", "text": "Je sais que c'est vrai. Je connais Rome."}, {"lang": "es", "text": "Sé que es verdad. Conozco Roma."}],
    "examples": [
      {"correct": "So nuotare.", "wrong": "Conosco nuotare.", "note": "Know how = sapere."},
      {"correct": "Conosco tuo fratello.", "wrong": "So tuo fratello.", "note": "Know a person = conoscere."},
    ],
  },
  {
    "id": "en-it-partitives",
    "direction": "en-it",
    "level": "a1",
    "category": "Articles",
    "title": "I want some water",
    "youThink": "I want some water → Voglio qualche acqua",
    "youSay": "Voglio qualche acqua.",
    "nativeSay": "Voglio dell'acqua.",
    "why": "Italian uses partitive articles (del, della, dei, degli, delle) for unspecified quantities of uncountable nouns. English uses SOME or no article. 'Qualche' means 'a few' and is only used with countable plural nouns.",
    "tip": "Uncountable nouns: dell'acqua, del pane, del vino. Countable plural: qualche volta, qualche giorno.",
    "parallels": [{"lang": "it", "text": "Voglio dell'acqua."}, {"lang": "fr", "text": "Je veux de l'eau."}, {"lang": "es", "text": "Quiero agua."}],
    "examples": [
      {"correct": "Mangio della pasta.", "wrong": "Mangio qualche pasta.", "note": "Pasta is uncountable: della."},
      {"correct": "Ho qualche amico.", "wrong": "Ho degli amico.", "note": "Amici is countable plural: qualche."},
    ],
  },
  {
    "id": "en-it-possessives",
    "direction": "en-it",
    "level": "a1",
    "category": "Possession",
    "title": "My book",
    "youThink": "My book → Mia libro",
    "youSay": "Mia libro.",
    "nativeSay": "Il mio libro.",
    "why": "Italian possessive adjectives (mio, tuo, suo, nostro, vostro, loro) always need the definite article before them (il mio, la mia, i miei, le mie). English never uses an article with possessives.",
    "tip": "Italian: article + possessive. Il mio, la tua, i suoi. English: just the possessive.",
    "parallels": [{"lang": "it", "text": "Il mio libro."}, {"lang": "fr", "text": "Mon livre."}, {"lang": "es", "text": "Mi libro."}],
    "examples": [
      {"correct": "La mia casa è grande.", "wrong": "Mia casa è grande.", "note": "Never omit the article with possessives."},
      {"correct": "I miei genitori.", "wrong": "Miei genitori.", "note": "I miei, not just miei."},
    ],
  },
  {
    "id": "en-it-essere-stare",
    "direction": "en-it",
    "level": "a1",
    "category": "Verbs",
    "title": "I am here",
    "youThink": "I am here → Io sono qui",
    "youSay": "Io sto qui.",
    "nativeSay": "Io sono qui.",
    "why": "Italian distinguishes between ESSERE (permanent state, identity, location) and STARE (temporary state, health, location with intent). For simple location, use ESSERE. STARE implies 'staying/remaining' or is used with certain fixed expressions.",
    "tip": "Location: sono. Health/condition: sto. Sto bene. Sono a casa.",
    "parallels": [{"lang": "it", "text": "Sono qui. Sto bene."}, {"lang": "fr", "text": "Je suis ici. Je vais bien."}, {"lang": "es", "text": "Estoy aquí. Estoy bien."}],
    "examples": [
      {"correct": "Sono in ufficio.", "wrong": "Sto in ufficio.", "note": "Simple location: essere."},
      {"correct": "Sto a casa oggi.", "wrong": "Sono a casa oggi.", "note": "Stare a casa = staying home (intentional)."},
    ],
  },
  {
    "id": "en-it-gerund",
    "direction": "en-it",
    "level": "a2",
    "category": "Verbs",
    "title": "I am eating",
    "youThink": "I am eating → Io sono mangiando",
    "youSay": "Io sono mangiando.",
    "nativeSay": "Sto mangiando.",
    "why": "Italian present continuous uses STARE + gerund (-ando/-endo), not ESSERE + gerund. 'Sto mangiando' = I am eating. 'Sono mangiando' is incorrect.",
    "tip": "Present continuous: Sto + mangiando. Never Sono + mangiando.",
    "parallels": [{"lang": "it", "text": "Sto mangiando."}, {"lang": "fr", "text": "Je suis en train de manger."}, {"lang": "es", "text": "Estoy comiendo."}],
    "examples": [
      {"correct": "Sto leggendo un libro.", "wrong": "Sono leggendo un libro.", "note": "Stare, not essere."},
      {"correct": "Stiamo parlando.", "wrong": "Siamo parlando.", "note": "Stiamo = we are (doing)."},
    ],
  },
  {
    "id": "en-it-piacere",
    "direction": "en-it",
    "level": "a1",
    "category": "Verbs",
    "title": "I like pizza",
    "youThink": "I like pizza → Io piaccio la pizza",
    "youSay": "Io piaccio la pizza.",
    "nativeSay": "Mi piace la pizza.",
    "why": "Italian PIACERE works backwards from English LIKE. 'Mi piace' literally means 'It pleases to me.' The thing liked is the subject, and the person is the indirect object. English: I (subject) like pizza. Italian: Pizza (subject) pleases to-me.",
    "tip": "Mi piace (singular subject) / Mi piacciono (plural subject). The thing liked determines the verb form.",
    "parallels": [{"lang": "it", "text": "Mi piace la pizza. Mi piacciono gli spaghetti."}, {"lang": "fr", "text": "J'aime la pizza."}, {"lang": "es", "text": "Me gusta la pizza."}],
    "examples": [
      {"correct": "Mi piacciono i libri.", "wrong": "Mi piace i libri.", "note": "Libri is plural: piacciono."},
      {"correct": "Ti piace il calcio?", "wrong": "Tu piaci il calcio?", "note": "Never use piacere as a regular transitive verb."},
    ],
  },
  {
    "id": "en-it-mancare",
    "direction": "en-it",
    "level": "a2",
    "category": "Verbs",
    "title": "I miss you",
    "youThink": "I miss you → Io manco te",
    "youSay": "Io manco te.",
    "nativeSay": "Mi manchi.",
    "why": "Italian MANCARE works like PIACERE — backwards from English. 'Mi manchi' literally means 'You are missing to me.' The person missed is the subject, and the feeler is the indirect object.",
    "tip": "Mi manchi = I miss you. Ti manco = You miss me. Works exactly like piacere.",
    "parallels": [{"lang": "it", "text": "Mi manchi. Mi manca Roma."}, {"lang": "fr", "text": "Tu me manques."}, {"lang": "es", "text": "Me extrañas. / Me faltas."}],
    "examples": [
      {"correct": "Mi manca la mia famiglia.", "wrong": "Manco la mia famiglia.", "note": "Family is singular subject: manca."},
      {"correct": "Ci manchi.", "wrong": "Vi manchiamo.", "note": "We miss you = Ci manchi (not Ti manchiamo)."},
    ],
  },
  {
    "id": "en-it-fare-freddo",
    "direction": "en-it",
    "level": "a1",
    "category": "Weather",
    "title": "It is cold",
    "youThink": "It is cold → È freddo",
    "youSay": "È freddo.",
    "nativeSay": "Fa freddo.",
    "why": "Italian weather expressions use FARE (to make/do), not ESSERE. 'Fa freddo' = It makes cold. English uses 'It is.'",
    "tip": "Weather: fa caldo, fa freddo, fa bel tempo, fa brutto tempo. Never è freddo for weather.",
    "parallels": [{"lang": "it", "text": "Fa freddo. Fa caldo."}, {"lang": "fr", "text": "Il fait froid. Il fait chaud."}, {"lang": "es", "text": "Hace frío. Hace calor."}],
    "examples": [
      {"correct": "Oggi fa molto caldo.", "wrong": "Oggi è molto caldo.", "note": "Weather = fare."},
      {"correct": "Fa vento.", "wrong": "È vento.", "note": "Fa vento = it's windy."},
    ],
  },
  {
    "id": "en-it-andare-bene",
    "direction": "en-it",
    "level": "a1",
    "category": "Expressions",
    "title": "How are you?",
    "youThink": "How are you? → Come sei?",
    "youSay": "Come sei?",
    "nativeSay": "Come stai? / Come va?",
    "why": "'How are you?' asks about your state/condition, not your identity. In Italian, you use STARE (state) or ANDARE (going). 'Come sei?' means 'What are you like?' (personality/appearance).",
    "tip": "How are you? = Come stai? / Come va? What are you like? = Come sei?",
    "parallels": [{"lang": "it", "text": "Come stai? / Come va?"}, {"lang": "fr", "text": "Comment vas-tu? / Ça va?"}, {"lang": "es", "text": "¿Cómo estás? / ¿Qué tal?"}],
    "examples": [
      {"correct": "Come stai oggi?", "wrong": "Come sei oggi?", "note": "Stai = state. Sei = identity."},
      {"correct": "Tutto bene, grazie.", "wrong": "Tutto buono, grazie.", "note": "Bene (adverb) = well. Buono (adjective) = good."},
    ],
  },
  {
    "id": "en-it-false-friend-fabric",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "The fabric of society",
    "youThink": "The fabric of society → La fabbrica della società",
    "youSay": "La fabbrica della società.",
    "nativeSay": "Il tessuto della società.",
    "why": "'Fabbrica' in Italian means FACTORY, not FABRIC. 'Fabric' in English = tessuto/stoffa. 'Fabbrica' in Italian = factory/plant.",
    "tip": "Fabbrica = factory. Tessuto/stoffa = fabric/cloth.",
    "parallels": [{"lang": "it", "text": "La fabbrica = the factory."}, {"lang": "fr", "text": "L'usine = the factory. Le tissu = the fabric."}, {"lang": "es", "text": "La fábrica = the factory. La tela = the fabric."}],
    "examples": [
      {"correct": "Lavoro in una fabbrica.", "wrong": "Lavoro in una fabrica.", "note": "Fabbrica = factory."},
      {"correct": "Questo tessuto è morbido.", "wrong": "Questa fabbrica è morbida.", "note": "Tessuto = fabric."},
    ],
  },
  {
    "id": "en-it-false-friend-parents",
    "direction": "en-it",
    "level": "a1",
    "category": "False Friends",
    "title": "My parents",
    "youThink": "My parents → I miei parenti",
    "youSay": "I miei parenti.",
    "nativeSay": "I miei genitori.",
    "why": "'Parente' in Italian means RELATIVE (any family member), not PARENT. 'Parents' in English = genitori. 'Parenti' in Italian = relatives.",
    "tip": "Genitori = parents. Parenti = relatives.",
    "parallels": [{"lang": "it", "text": "I miei genitori = my parents. I miei parenti = my relatives."}, {"lang": "fr", "text": "Mes parents = my parents. Mes proches = my relatives."}, {"lang": "es", "text": "Mis padres = my parents. Mis parientes = my relatives."}],
    "examples": [
      {"correct": "I miei genitori vivono a Roma.", "wrong": "I miei parenti vivono a Roma.", "note": "Parenti = relatives, not parents."},
      {"correct": "Ho molti parenti in Sicilia.", "wrong": "Ho molti genitori in Sicilia.", "note": "Many relatives, not many parents."},
    ],
  },
  {
    "id": "en-it-false-friend-magazine",
    "direction": "en-it",
    "level": "a1",
    "category": "False Friends",
    "title": "I read a magazine",
    "youThink": "I read a magazine → Leggo una magazzino",
    "youSay": "Leggo una magazzino.",
    "nativeSay": "Leggo una rivista.",
    "why": "'Magazzino' in Italian means WAREHOUSE/STOREHOUSE, not MAGAZINE. 'Magazine' in English = rivista. 'Magazzino' in Italian = warehouse/stockroom.",
    "tip": "Rivista = magazine. Magazzino = warehouse.",
    "parallels": [{"lang": "it", "text": "Una rivista = a magazine. Un magazzino = a warehouse."}, {"lang": "fr", "text": "Un magazine = a magazine. Un entrepôt = a warehouse."}, {"lang": "es", "text": "Una revista = a magazine. Un almacén = a warehouse."}],
    "examples": [
      {"correct": "Compro una rivista all'aeroporto.", "wrong": "Compro una magazzino all'aeroporto.", "note": "Rivista = magazine."},
      {"correct": "Il magazzino è pieno.", "wrong": "La rivista è piena.", "note": "Magazzino = warehouse (not magazine)."},
    ],
  },
  {
    "id": "en-it-false-friend-sensible",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "He is very sensible",
    "youThink": "He is very sensible → È molto sensibile",
    "youSay": "È molto sensibile.",
    "nativeSay": "È molto ragionevole / pratico.",
    "why": "'Sensibile' in Italian means SENSITIVE (emotionally or physically reactive), not SENSIBLE (practical/reasonable). 'Sensible' in English = ragionevole/pratico. 'Sensibile' in Italian = sensitive.",
    "tip": "Sensibile = sensitive. Ragionevole/sensato = sensible.",
    "parallels": [{"lang": "it", "text": "È molto sensibile. = He is very sensitive."}, {"lang": "fr", "text": "Il est très sensible. = He is very sensitive."}, {"lang": "es", "text": "Es muy sensible. = He is very sensitive."}],
    "examples": [
      {"correct": "È una persona ragionevole.", "wrong": "È una persona sensibile. (meaning sensible)", "note": "Ragionevole = sensible. Sensibile = sensitive."},
      {"correct": "Ha la pelle sensibile.", "wrong": "Ha la pelle sensible.", "note": "Sensibile = sensitive (skin)."},
    ],
  },
  {
    "id": "en-it-false-friend-convenient",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "It is convenient",
    "youThink": "It is convenient → È conveniente",
    "youSay": "È conveniente.",
    "nativeSay": "È comodo / È pratico.",
    "why": "'Conveniente' in Italian means CHEAP/GOOD VALUE (price), not CONVENIENT (easy/practical). 'Convenient' in English = comodo/pratico. 'Conveniente' in Italian = good price/value.",
    "tip": "Conveniente = good value/cheap. Comodo/pratico = convenient.",
    "parallels": [{"lang": "it", "text": "È conveniente = It's good value."}, {"lang": "fr", "text": "C'est pratique = It's convenient."}, {"lang": "es", "text": "Es conveniente (in Spain = advisable). Es cómodo = convenient."}],
    "examples": [
      {"correct": "Questo ristorante è conveniente.", "wrong": "Questo ristorante è comodo.", "note": "Conveniente = good prices."},
      {"correct": "È comodo prendere l'autobus.", "wrong": "È conveniente prendere l'autobus.", "note": "Comodo = convenient/easy."},
    ],
  },
  {
    "id": "en-it-false-friend-terrible",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "A terrible experience",
    "youThink": "A terrible experience → Un'esperienza terribile",
    "youSay": "Un'esperienza terribile.",
    "nativeSay": "Un'esperienza terribile.",
    "why": "Wait — 'terribile' DOES mean terrible! But in Italian it can also mean AMAZING/FORMIDABLE in colloquial speech. 'Un concerto terribile' could mean an incredibly good concert. Context matters.",
    "tip": "Terribile usually = terrible. But colloquially it can mean 'incredible' (good or bad).",
    "parallels": [{"lang": "it", "text": "Terribile = terrible OR amazing (colloquial)."}, {"lang": "fr", "text": "Terrible = terrible OR amazing."}, {"lang": "es", "text": "Terrible = terrible."}],
    "examples": [
      {"correct": "Un film terribile.", "wrong": "Un film terrible.", "note": "Terribile (with -ibile), not terrible."},
      {"correct": "Ha una voce terribile! (compliment)", "wrong": "Ha una voce terrible!", "note": "Colloquial: terribile can mean amazing."},
    ],
  },
  {
    "id": "en-it-false-friend-pretend",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "He pretends to be sick",
    "youThink": "He pretends to be sick → Lui pretende di essere malato",
    "youSay": "Lui pretende di essere malato.",
    "nativeSay": "Lui finge di essere malato.",
    "why": "'Pretendere' in Italian means TO DEMAND/EXPECT, not TO PRETEND. 'Pretend' in English = fingere/simulare. 'Pretendere' in Italian = to demand, to expect.",
    "tip": "Pretendere = to demand/expect. Fingere = to pretend.",
    "parallels": [{"lang": "it", "text": "Pretendere = to demand. Fingere = to pretend."}, {"lang": "fr", "text": "Prétendre = to claim. Faire semblant = to pretend."}, {"lang": "es", "text": "Pretender = to try/attempt. Fingir = to pretend."}],
    "examples": [
      {"correct": "Pretende un aumento di stipendio.", "wrong": "Finge un aumento di stipendio.", "note": "Pretendere = demand/expect."},
      {"correct": "Finge di dormire.", "wrong": "Pretende di dormire.", "note": "Fingere = pretend."},
    ],
  },
  {
    "id": "en-it-false-friend-grave",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "A grave situation",
    "youThink": "A grave situation → Una situazione grave",
    "youSay": "Una situazione grave.",
    "nativeSay": "Una situazione grave.",
    "why": "'Grave' in Italian means SERIOUS/SEVERE, not necessarily related to a tomb. But 'grave' in English can mean both serious AND a burial place. In Italian, 'tomba' is the burial place.",
    "tip": "Grave = serious. Tomba = grave (burial).",
    "parallels": [{"lang": "it", "text": "Una situazione grave."}, {"lang": "fr", "text": "Une situation grave."}, {"lang": "es", "text": "Una situación grave."}],
    "examples": [
      {"correct": "È un problema grave.", "wrong": "È un problema tomba.", "note": "Grave = serious."},
      {"correct": "La tomba è nel cimitero.", "wrong": "La grave è nel cimitero.", "note": "Tomba = grave (burial place)."},
    ],
  },
  {
    "id": "en-it-false-friend-moral",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "The moral of the story",
    "youThink": "The moral of the story → Il morale della storia",
    "youSay": "Il morale della storia.",
    "nativeSay": "La morale della storia.",
    "why": "'Morale' in Italian (feminine: la morale) means MORAL/LESSON of a story. 'Morale' in English = the ethical lesson. But in Italian 'il morale' (masculine) means MOOD/SPIRITS. Gender changes the meaning.",
    "tip": "La morale = moral (lesson). Il morale = mood/spirits.",
    "parallels": [{"lang": "it", "text": "La morale = moral lesson. Il morale = mood."}, {"lang": "fr", "text": "La morale = moral lesson. Le moral = mood."}, {"lang": "es", "text": "La moraleja = moral lesson. El ánimo = mood."}],
    "examples": [
      {"correct": "La morale è: non mentire.", "wrong": "Il morale è: non mentire.", "note": "La morale = the moral."},
      {"correct": "Il morale è alto.", "wrong": "La morale è alta.", "note": "Il morale = the mood."},
    ],
  },
  {
    "id": "en-it-false-friend-patent",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "He has a patent",
    "youThink": "He has a patent → Ha un patente",
    "youSay": "Ha un patente.",
    "nativeSay": "Ha un brevetto.",
    "why": "'Patente' in Italian means DRIVER'S LICENSE, not PATENT. 'Patent' in English = brevetto. 'Patente' in Italian = driving licence.",
    "tip": "Brevetto = patent. Patente = driver's license.",
    "parallels": [{"lang": "it", "text": "Brevetto = patent. Patente = driver's license."}, {"lang": "fr", "text": "Brevet = patent. Permis = driver's license."}, {"lang": "es", "text": "Patente = patent. Carnet de conducir = driver's license."}],
    "examples": [
      {"correct": "Ha inventato qualcosa di nuovo e ha preso un brevetto.", "wrong": "Ha inventato qualcosa e ha preso una patente.", "note": "Brevetto = patent."},
      {"correct": "Ha preso la patente l'anno scorso.", "wrong": "Ha preso il brevetto l'anno scorso.", "note": "Patente = driver's license."},
    ],
  },
  {
    "id": "en-it-false-friend-realize",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "I realize my dream",
    "youThink": "I realize my dream → Realizzo il mio sogno",
    "youSay": "Realizzo il mio sogno.",
    "nativeSay": "Realizzo il mio sogno. / Capisco che...",
    "why": "'Realizzare' in Italian means TO ACHIEVE/MAKE REAL (a dream, a project), not TO REALIZE (to become aware). 'Realize' in English (become aware) = rendersi conto / capire. 'Realizzare' in Italian = to achieve.",
    "tip": "Realizzare = achieve/make real. Rendersi conto = realize (become aware).",
    "parallels": [{"lang": "it", "text": "Realizzare = achieve. Rendersi conto = realize (awareness)."}, {"lang": "fr", "text": "Réaliser = achieve. Se rendre compte = realize."}, {"lang": "es", "text": "Realizar = achieve. Darse cuenta = realize."}],
    "examples": [
      {"correct": "Ho realizzato il mio sogno.", "wrong": "Ho realizzato che era tardi.", "note": "For awareness: Mi sono reso conto."},
      {"correct": "Mi sono reso conto del problema.", "wrong": "Ho realizzato il problema.", "note": "Rendersi conto = become aware."},
    ],
  },
  {
    "id": "en-it-false-friend-resume",
    "direction": "en-it",
    "level": "a2",
    "category": "False Friends",
    "title": "My resume",
    "youThink": "My resume → Il mio resume",
    "youSay": "Il mio resume.",
    "nativeSay": "Il mio curriculum.",
    "why": "'Riassumere' in Italian means TO SUMMARIZE/RESUME (an activity), not a CV. 'Resume' in English (CV) = curriculum vitae. 'Resumere' (not a real Italian word) is sometimes misused for CV.",
    "tip": "Curriculum = CV/resume. Riassumere = to summarize.",
    "parallels": [{"lang": "it", "text": "Il mio curriculum."}, {"lang": "fr", "text": "Mon CV."}, {"lang": "es", "text": "Mi currículum."}],
    "examples": [
      {"correct": "Ho inviato il mio curriculum.", "wrong": "Ho inviato il mio resume.", "note": "Curriculum = CV."},
      {"correct": "Per riassumere...", "wrong": "Per resume...", "note": "Riassumere = to summarize."},
    ],
  },
  {
    "id": "en-it-question-order",
    "direction": "en-it",
    "level": "a1",
    "category": "Questions",
    "title": "Do you speak Italian?",
    "youThink": "Do you speak Italian? → Fai parlare italiano?",
    "youSay": "Fai parlare italiano?",
    "nativeSay": "Parli italiano?",
    "why": "Italian does not use DO-support for questions. You simply raise intonation or put the subject after the verb. 'Do you speak?' → 'Parli?' English needs 'do/does/did' for questions and negatives. Italian never does.",
    "tip": "Italian questions: same word order, raise voice. Or verb + subject: Parli tu?",
    "parallels": [{"lang": "it", "text": "Parli italiano?"}, {"lang": "fr", "text": "Parles-tu italien?"}, {"lang": "es", "text": "¿Hablas italiano?"}],
    "examples": [
      {"correct": "Hai fame?", "wrong": "Do hai fame?", "note": "Never use 'do' in Italian."},
      {"correct": "Non capisco.", "wrong": "Non faccio capire.", "note": "Negatives: just NON + verb."},
    ],
  },
  {
    "id": "en-it-ci-sono",
    "direction": "en-it",
    "level": "a1",
    "category": "Existence",
    "title": "There is a book",
    "youThink": "There is a book → Lì è un libro",
    "youSay": "Lì è un libro.",
    "nativeSay": "C'è un libro.",
    "why": "Italian uses CI + È/Sono for 'there is/there are.' Literally: 'It here is a book.' 'Lì' means 'there' (location), not 'there is.' English 'there' is overloaded — Italian separates location (lì) from existence (c'è).",
    "tip": "There is = C'è. There are = Ci sono. Location 'there' = lì/là.",
    "parallels": [{"lang": "it", "text": "C'è un libro. Ci sono tre libri."}, {"lang": "fr", "text": "Il y a un livre."}, {"lang": "es", "text": "Hay un libro."}],
    "examples": [
      {"correct": "C'è un problema.", "wrong": "Lì è un problema.", "note": "C'è = there is. Lì = over there."},
      {"correct": "Ci sono molte persone.", "wrong": "Lì sono molte persone.", "note": "Ci sono = there are."},
    ],
  },
  {
    "id": "en-it-verb-rompere",
    "direction": "en-it",
    "level": "a1",
    "category": "Verbs",
    "title": "I break the glass",
    "youThink": "I break the glass → Io rompo il vetro",
    "youSay": "Io rompo il vetro.",
    "nativeSay": "Rompo il vetro.",
    "why": "Italian often drops the subject pronoun because the verb ending shows who is acting. 'Rompo' already means 'I break.' Adding 'Io' is grammatically correct but sounds emphatic or unnatural in simple statements.",
    "tip": "Drop io/tu/lui/lei when the verb ending makes it clear. Use pronouns for emphasis or contrast.",
    "parallels": [{"lang": "it", "text": "Rompo il vetro. (No 'io' needed)"}, {"lang": "fr", "text": "Je casse le verre. (Subject required)"}, {"lang": "es", "text": "Rompo el vidrio. (Subject often dropped)"}],
    "examples": [
      {"correct": "Parlo italiano.", "wrong": "Io parlo italiano. (sounds emphatic)", "note": "Simple statement: drop the pronoun."},
      {"correct": "Io parlo italiano, ma lui no.", "wrong": "Parlo italiano, ma lui no.", "note": "Contrast: keep the pronoun."},
    ],
  },
  {
    "id": "en-it-adj-qualche",
    "direction": "en-it",
    "level": "a1",
    "category": "Quantifiers",
    "title": "Some friends",
    "youThink": "Some friends → Qualche amici",
    "youSay": "Qualche amici.",
    "nativeSay": "Qualche amico.",
    "why": "'Qualche' in Italian is always followed by a SINGULAR noun, even though it means 'some/a few.' It acts like a plural quantifier but grammatically takes singular. English 'some' takes plural.",
    "tip": "Qualche + singular noun = some/few. Qualche amico = a few friends.",
    "parallels": [{"lang": "it", "text": "Qualche amico. Qualche volta."}, {"lang": "fr", "text": "Quelques amis."}, {"lang": "es", "text": "Algunos amigos."}],
    "examples": [
      {"correct": "Ho qualche domanda.", "wrong": "Ho qualche domande.", "note": "Qualche + singular."},
      {"correct": "Vengo qualche giorno.", "wrong": "Vengo qualche giorni.", "note": "Giorno, not giorni, after qualche."},
    ],
  },
  {
    "id": "en-it-fare-causative",
    "direction": "en-it",
    "level": "a2",
    "category": "Verbs",
    "title": "I have my hair cut",
    "youThink": "I have my hair cut → Ho i miei capelli tagliati",
    "youSay": "Ho i miei capelli tagliati.",
    "nativeSay": "Mi faccio tagliare i capelli.",
    "why": "Italian uses the causative construction FARSI + infinitive for services you have done to you. English uses 'have something done' or 'get something done.' Italian: 'I make myself cut the hair' = I get my hair cut.",
    "tip": "Farsi + infinitive = have/get something done to you. Mi faccio tagliare = I get cut.",
    "parallels": [{"lang": "it", "text": "Mi faccio tagliare i capelli."}, {"lang": "fr", "text": "Je me fais couper les cheveux."}, {"lang": "es", "text": "Me corto el pelo. / Me hago cortar el pelo."}],
    "examples": [
      {"correct": "Mi faccio lavare la macchina.", "wrong": "Ho la macchina lavata.", "note": "Farsi lavare = get washed."},
      {"correct": "Si è fatta fare le unghie.", "wrong": "Ha le unghie fatte.", "note": "Farsi fare = get done."},
    ],
  },
  {
    "id": "en-it-ancora-gia",
    "direction": "en-it",
    "level": "a1",
    "category": "Time",
    "title": "I am still here",
    "youThink": "I am still here → Sono sempre qui",
    "youSay": "Sono sempre qui.",
    "nativeSay": "Sono ancora qui.",
    "why": "Italian distinguishes between ANCORA (still/yet), GIÀ (already), and SEMPRE (always). 'Still' in positive sentences = ancora. 'Always' = sempre. 'Already' = già.",
    "tip": "Ancora = still (positive). Non...ancora = not yet. Già = already. Sempre = always.",
    "parallels": [{"lang": "it", "text": "Sono ancora qui. Sono già qui. Sono sempre qui."}, {"lang": "fr", "text": "Je suis encore ici. Je suis déjà ici. Je suis toujours ici."}, {"lang": "es", "text": "Todavía estoy aquí. Ya estoy aquí. Siempre estoy aquí."}],
    "examples": [
      {"correct": "Non ho ancora mangiato.", "wrong": "Non ho sempre mangiato.", "note": "Not yet = non...ancora."},
      {"correct": "Hai già finito?", "wrong": "Hai ancora finito?", "note": "Already = già."},
    ],
  },
  {
    "id": "en-it-bere-mangiare",
    "direction": "en-it",
    "level": "a1",
    "category": "Verbs",
    "title": "I eat soup",
    "youThink": "I eat soup → Mangio la zuppa",
    "youSay": "Mangio la zuppa.",
    "nativeSay": "Mangio la zuppa. / Bevo la zuppa?",
    "why": "In Italian, you can both MANGIARE (eat) and BERE (drink) soup — it depends on consistency. But for all meals, Italian uses the definite article: 'Mangio la pasta' not just 'Mangio pasta.'",
    "tip": "Italian uses articles with general categories of food: mangio la pasta, bevo il vino.",
    "parallels": [{"lang": "it", "text": "Mangio la zuppa. Bevo il caffè."}, {"lang": "fr", "text": "Je mange la soupe. Je bois le café."}, {"lang": "es", "text": "Como la sopa. Bebo el café."}],
    "examples": [
      {"correct": "Mangio la carne.", "wrong": "Mangio carne.", "note": "Use article with food categories."},
      {"correct": "Bevo il tè.", "wrong": "Bevo tè.", "note": "Il tè, not just tè."},
    ],
  },
  {
    "id": "en-it-dovere-potere",
    "direction": "en-it",
    "level": "a1",
    "category": "Modals",
    "title": "I must go",
    "youThink": "I must go → Devo andare",
    "youSay": "Devo andare.",
    "nativeSay": "Devo andare. / Dovrei andare.",
    "why": "Italian DOVERE covers both MUST (strong obligation) and HAVE TO (external obligation). But Italian also uses DOVREI for 'should/ought to.' English separates must/have to/should more strictly.",
    "tip": "Devo = I must/have to. Dovrei = I should. Non devo = I must not (prohibition). Non dovrei = I shouldn't.",
    "parallels": [{"lang": "it", "text": "Devo andare. Dovrei andare."}, {"lang": "fr", "text": "Je dois aller. Je devrais aller."}, {"lang": "es", "text": "Debo ir. Debería ir."}],
    "examples": [
      {"correct": "Non devi fumare.", "wrong": "Non puoi fumare. (if meaning prohibition)", "note": "Non devi = must not (prohibition). Non puoi = cannot (ability)."},
      {"correct": "Dovrei studiare di più.", "wrong": "Devo studiare di più. (if meaning advice, not obligation)", "note": "Dovrei = should. Devo = must."},
    ],
  },
  {
    "id": "en-it-troppo-abbastanza",
    "direction": "en-it",
    "level": "a1",
    "category": "Quantifiers",
    "title": "It is too expensive",
    "youThink": "It is too expensive → È troppo costoso",
    "youSay": "È troppo costoso.",
    "nativeSay": "È troppo costoso.",
    "why": "Italian TROPPO and ABBASTANZA behave differently from English TOO and ENOUGH. 'Troppo' goes before the adjective. 'Abbastanza' also goes before. English 'enough' goes AFTER the adjective: 'good enough' vs 'abbastanza buono.'",
    "tip": "Troppo + adjective. Abbastanza + adjective. English: adjective + enough.",
    "parallels": [{"lang": "it", "text": "Troppo costoso. Abbastanza buono."}, {"lang": "fr", "text": "Trop cher. Assez bon."}, {"lang": "es", "text": "Demasiado caro. Bastante bueno."}],
    "examples": [
      {"correct": "È abbastanza buono.", "wrong": "È buono abbastanza.", "note": "Abbastanza before the adjective."},
      {"correct": "Non è abbastanza caldo.", "wrong": "Non è caldo abbastanza.", "note": "English: warm enough. Italian: abbastanza caldo."},
    ],
  },
  {
    "id": "en-it-fare-colazione",
    "direction": "en-it",
    "level": "a1",
    "category": "Expressions",
    "title": "I have breakfast",
    "youThink": "I have breakfast → Ho la colazione",
    "youSay": "Ho la colazione.",
    "nativeSay": "Faccio colazione.",
    "why": "Italian uses FARE (to make/do) for many daily activities: fare colazione, fare una passeggiata, fare la spesa, fare il bagno. English uses HAVE, GO, DO, TAKE depending on the activity.",
    "tip": "Fare colazione = have breakfast. Fare la spesa = go grocery shopping. Fare il bagno = take a bath.",
    "parallels": [{"lang": "it", "text": "Faccio colazione. Faccio una passeggiata."}, {"lang": "fr", "text": "Je prends le petit déjeuner. Je fais une promenade."}, {"lang": "es", "text": "Desayuno. Doy un paseo."}],
    "examples": [
      {"correct": "Faccio la doccia ogni mattina.", "wrong": "Prendo la doccia ogni mattina.", "note": "Fare la doccia = take a shower."},
      {"correct": "Faccio una passeggata nel parco.", "wrong": "Vado una passeggata nel parco.", "note": "Fare una passeggiata = go for a walk."},
    ],
  },
  {
    "id": "en-it-andare-a-cavallo",
    "direction": "en-it",
    "level": "a1",
    "category": "Expressions",
    "title": "I ride a bike",
    "youThink": "I ride a bike → Cavalco una bici",
    "youSay": "Cavalco una bici.",
    "nativeSay": "Vado in bicicletta.",
    "why": "Italian uses ANDARE IN + vehicle for riding/driving, not the verb 'to ride.' 'Andare in bicicletta' = go by bike. 'Andare in macchina' = go by car. CAVALCARE is only for horses.",
    "tip": "Andare in + vehicle. Andare a piedi = on foot. Andare in treno = by train.",
    "parallels": [{"lang": "it", "text": "Vado in bicicletta. Vado in macchina."}, {"lang": "fr", "text": "Je vais à vélo. Je vais en voiture."}, {"lang": "es", "text": "Voy en bicicleta. Voy en coche."}],
    "examples": [
      {"correct": "Vado al lavoro in autobus.", "wrong": "Guido l'autobus al lavoro.", "note": "Vado in autobus = I take the bus."},
      {"correct": "Vengo a piedi.", "wrong": "Cammino a piedi.", "note": "Vengo a piedi = I come on foot."},
    ],
  },
  {
    "id": "en-it-ora-che",
    "direction": "en-it",
    "level": "a2",
    "category": "Conjunctions",
    "title": "Now that you are here",
    "youThink": "Now that you are here → Adesso che sei qui",
    "youSay": "Adesso che sei qui.",
    "nativeSay": "Ora che sei qui.",
    "why": "'Ora' is more natural than 'adesso' in 'now that' constructions. Also, Italian uses the indicative after 'ora che' (not subjunctive) because it's a factual situation.",
    "tip": "Ora che + indicative = Now that... Appena + passato prossimo = As soon as...",
    "parallels": [{"lang": "it", "text": "Ora che sei qui, possiamo iniziare."}, {"lang": "fr", "text": "Maintenant que tu es là..."}, {"lang": "es", "text": "Ahora que estás aquí..."}],
    "examples": [
      {"correct": "Ora che lo so, posso aiutarti.", "wrong": "Adesso che lo sappia, posso aiutarti.", "note": "Ora che + indicative (so, not sappia)."},
      {"correct": "Appena è arrivato, siamo partiti.", "wrong": "Quando è arrivato, siamo partiti.", "note": "Appena = as soon as (more precise)."},
    ],
  },
  {
    "id": "en-it-di-che",
    "direction": "en-it",
    "level": "a1",
    "category": "Prepositions",
    "title": "What color is it?",
    "youThink": "What color is it? → Quale colore è?",
    "youSay": "Quale colore è?",
    "nativeSay": "Di che colore è?",
    "why": "Italian asks about qualities using DI + CHE: 'Di che colore?' = Of what color? 'Di che nazionalità?' = Of what nationality? English uses 'What...?' directly.",
    "tip": "Di che + noun = What...? Di che colore? Di che marca? Di che nazionalità?",
    "parallels": [{"lang": "it", "text": "Di che colore è?"}, {"lang": "fr", "text": "De quelle couleur est-ce?"}, {"lang": "es", "text": "¿De qué color es?"}],
    "examples": [
      {"correct": "Di che marca è la macchina?", "wrong": "Quale marca è la macchina?", "note": "Di che marca = what brand."},
      {"correct": "Di che nazionalità sei?", "wrong": "Quale nazionalità sei?", "note": "Di che nazionalità = what nationality."},
    ],
  },
  {
    "id": "en-it-mi-piace-plural",
    "direction": "en-it",
    "level": "a1",
    "category": "Verbs",
    "title": "I like cats",
    "youThink": "I like cats → Mi piace i gatti",
    "youSay": "Mi piace i gatti.",
    "nativeSay": "Mi piacciono i gatti.",
    "why": "With PIACERE, the SUBJECT determines the verb form. 'I gatti' is plural, so the verb must be plural: PIACCIONO. English 'I like cats' has 'I' as subject. Italian 'Mi piacciono i gatti' has 'i gatti' as subject.",
    "tip": "Mi piace (singular subject). Mi piacciono (plural subject). The thing liked is the boss.",
    "parallels": [{"lang": "it", "text": "Mi piace il gelato. Mi piacciono gli spaghetti."}, {"lang": "fr", "text": "J'aime la glace. J'aime les spaghetti."}, {"lang": "es", "text": "Me gusta el helado. Me gustan los espaguetis."}],
    "examples": [
      {"correct": "Ti piacciono questi film?", "wrong": "Ti piace questi film?", "note": "Film (plural) = piacciono."},
      {"correct": "Ci piace questa canzone.", "wrong": "Ci piacciono questa canzone.", "note": "Canzone (singular) = piace."},
    ],
  },
  {
    "id": "en-it-ne",
    "direction": "en-it",
    "level": "a2",
    "category": "Pronouns",
    "title": "I want three of them",
    "youThink": "I want three of them → Voglio tre di loro",
    "youSay": "Voglio tre di loro.",
    "nativeSay": "Ne voglio tre.",
    "why": "Italian uses the particle NE to replace 'of them/it' or to indicate 'some of' a previously mentioned thing. 'Ne voglio tre' = Of them, I want three. English needs the full phrase.",
    "tip": "Ne = of it/of them/some. Ne ho mangiati tre = I ate three of them. Ne voglio = I want some.",
    "parallels": [{"lang": "it", "text": "Ne voglio tre."}, {"lang": "fr", "text": "J'en veux trois."}, {"lang": "es", "text": "Quiero tres de ellos."}],
    "examples": [
      {"correct": "Ne ho comprati due.", "wrong": "Ho comprati due di loro.", "note": "Ne = of them."},
      {"correct": "Non ne ho più.", "wrong": "Non ho più di loro.", "note": "Non ne ho più = I don't have any more."},
    ],
  },
  {
    "id": "en-it-avverbi-frequenza",
    "direction": "en-it",
    "level": "a1",
    "category": "Adverbs",
    "title": "I always eat pasta",
    "youThink": "I always eat pasta → Io sempre mangio la pasta",
    "youSay": "Io sempre mangio la pasta.",
    "nativeSay": "Mangio sempre la pasta.",
    "why": "Italian adverbs of frequency (sempre, mai, spesso, raramente, qualche volta) usually go immediately AFTER the verb they modify. English puts them before the main verb: 'I always eat.' Italian: 'Mangio sempre.'",
    "tip": "Verb + adverb of frequency. Mangio sempre. Non vengo mai. Lavoro spesso.",
    "parallels": [{"lang": "it", "text": "Mangio sempre la pasta."}, {"lang": "fr", "text": "Je mange toujours des pâtes."}, {"lang": "es", "text": "Siempre como pasta."}],
    "examples": [
      {"correct": "Vado spesso al cinema.", "wrong": "Spesso vado al cinema.", "note": "Spesso after the verb."},
      {"correct": "Non mangio mai la carne.", "wrong": "Non mai mangio la carne.", "note": "Mai after the verb."},
    ],
  },
  {
    "id": "en-it-passive-si",
    "direction": "en-it",
    "level": "a2",
    "category": "Voice",
    "title": "Italian is spoken here",
    "youThink": "Italian is spoken here → L'italiano è parlato qui",
    "youSay": "L'italiano è parlato qui.",
    "nativeSay": "Qui si parla italiano.",
    "why": "Italian often uses the impersonal SI instead of the formal passive (essere + past participle). 'Si parla italiano' = One speaks Italian / Italian is spoken. It's more natural and common in spoken Italian.",
    "tip": "Si + third person verb = impersonal passive. Si parla, si mangia, si vive.",
    "parallels": [{"lang": "it", "text": "Qui si parla italiano."}, {"lang": "fr", "text": "On parle italien ici."}, {"lang": "es", "text": "Aquí se habla italiano."}],
    "examples": [
      {"correct": "In Italia si mangia bene.", "wrong": "In Italia è mangiato bene.", "note": "Si mangia = one eats / people eat."},
      {"correct": "Si può fumare?", "wrong": "È permesso fumare?", "note": "Si può = is it possible/allowed."},
    ],
  },
  {
    "id": "en-it-futuro-prossimo",
    "direction": "en-it",
    "level": "a2",
    "category": "Tenses",
    "title": "I am going to eat",
    "youThink": "I am going to eat → Vado a mangiare",
    "youSay": "Vado a mangiare.",
    "nativeSay": "Vado a mangiare. / Mangerò.",
    "why": "Italian uses both the simple future (mangerò) and the 'going to' construction (vado a + infinitive) for future plans. The 'vado a' form is more common in spoken Italian for immediate future, just like English.",
    "tip": "Immediate future: vado a + infinitive. General future: -erò/-irò/-arò endings.",
    "parallels": [{"lang": "it", "text": "Vado a mangiare. Mangerò domani."}, {"lang": "fr", "text": "Je vais manger. Je mangerai demain."}, {"lang": "es", "text": "Voy a comer. Comeré mañana."}],
    "examples": [
      {"correct": "Stasera vado a vedere un film.", "wrong": "Stasera andrò a vedere un film.", "note": "Vado a vedere = more natural for tonight."},
      {"correct": "L'anno prossimo viaggerò in Giappone.", "wrong": "L'anno prossimo vado a viaggiare in Giappone.", "note": "Future = simpler for distant plans."},
    ],
  },
  {
    "id": "en-it-bello-articolo",
    "direction": "en-it",
    "level": "a1",
    "category": "Adjectives",
    "title": "A beautiful day",
    "youThink": "A beautiful day → Una bella giornata",
    "youSay": "Una bella giornata.",
    "nativeSay": "Una bellissima giornata. / Una bella giornata.",
    "why": "'Bello' changes form before nouns to match the article: bel (masc sing before consonant), bell' (before vowel), bei (masc plural), begli (masc plural before vowel). It does NOT stay 'bello' before the noun.",
    "tip": "Bello before noun: bel, bell', bei, begli, bella, belle. After noun: bello, belli.",
    "parallels": [{"lang": "it", "text": "Un bel giorno. Un bell'uomo. Una bella giornata."}, {"lang": "fr", "text": "Un beau jour. Un bel homme."}, {"lang": "es", "text": "Un hermoso día. Un hombre guapo."}],
    "examples": [
      {"correct": "È un bel film.", "wrong": "È un bello film.", "note": "Bel before masculine noun."},
      {"correct": "Sono begli amici.", "wrong": "Sono belli amici.", "note": "Begli before vowel."},
    ],
  },
  {
    "id": "en-it-dimmi",
    "direction": "en-it",
    "level": "a1",
    "category": "Imperative",
    "title": "Tell me",
    "youThink": "Tell me → Dica mi",
    "youSay": "Dica mi.",
    "nativeSay": "Dimmi.",
    "why": "Italian attaches object pronouns to the imperative in the TU and VOI forms: dimmi, dimmelo, dacci, fammi. In the formal LEI form, they stay separate: Mi dica. With negative imperatives, they can go before or after.",
    "tip": "Tu imperative + pronoun: Dimmi. Dammi. Fammi vedere. Lei imperative: Mi dica. Mi dia.",
    "parallels": [{"lang": "it", "text": "Dimmi la verità. Mi dica, per favore."}, {"lang": "fr", "text": "Dis-moi. Dites-moi."}, {"lang": "es", "text": "Dime. Dígame."}],
    "examples": [
      {"correct": "Dimmi tutto.", "wrong": "Dica mi tutto.", "note": "Dimmi = tell me (tu)."},
      {"correct": "Fammi vedere.", "wrong": "Fai mi vedere.", "note": "Fammi = make me see = show me."},
    ],
  },
  {
    "id": "en-it-ci-metto",
    "direction": "en-it",
    "level": "a2",
    "category": "Expressions",
    "title": "It takes me 10 minutes",
    "youThink": "It takes me 10 minutes → Mi prende dieci minuti",
    "youSay": "Mi prende dieci minuti.",
    "nativeSay": "Ci metto dieci minuti.",
    "why": "Italian uses CI METTO for time a PERSON takes to do something. 'Ci voglio' (with volere) is also used but 'ci metto' is more precise for active effort. 'Ci metto' = I put myself (time) into it.",
    "tip": "Ci metto = I take (time to do something). Ci metto un'ora = It takes me an hour.",
    "parallels": [{"lang": "it", "text": "Ci metto dieci minuti."}, {"lang": "fr", "text": "J'y mets dix minutes."}, {"lang": "es", "text": "Tardo diez minutos."}],
    "examples": [
      {"correct": "Ci metto due ore per andare a lavoro.", "wrong": "Prendo due ore per andare a lavoro.", "note": "Ci metto = I take (time)."},
      {"correct": "Quanto ci metti?", "wrong": "Quanto prendi?", "note": "Quanto ci metti = How long do you take?"},
    ],
  },
]

print(f"Generated {len(new_en_it)} new en-it lessons")
with open('scripts/new_en_it.json', 'w', encoding='utf-8') as f:
    json.dump(new_en_it, f, ensure_ascii=False, indent=2)
