import json

# Load new en-it lessons
with open('scripts/new_en_it.json', 'r', encoding='utf-8') as f:
    new_en_it = json.load(f)

# Define new it-en lessons
new_it_en = [
  {"id": "it-en-present-continuous", "direction": "it-en", "level": "a1", "category": "Tenses", "title": "Sto mangiando", "youThink": "Sto mangiando → I eat", "youSay": "I eat.", "nativeSay": "I am eating.", "why": "English uses the present continuous (BE + -ing) for actions happening RIGHT NOW. The simple present is for habits and routines. Italian uses the simple present for both. 'Sto mangiando' must become 'I am eating,' not 'I eat.'", "tip": "Now = -ing. Always. I am eating, I am reading, I am working.", "parallels": [{"lang": "en", "text": "I am eating."}, {"lang": "it", "text": "Sto mangiando."}, {"lang": "fr", "text": "Je suis en train de manger."}], "examples": [{"correct": "I am eating now.", "wrong": "I eat now.", "note": "Now requires -ing."}, {"correct": "What are you doing?", "wrong": "What do you do?", "note": "'What do you do?' = What's your job? 'What are you doing?' = Right now?"}]},
  {"id": "it-en-phrasal-get-up", "direction": "it-en", "level": "a1", "category": "Phrasal Verbs", "title": "Mi alzo", "youThink": "Mi alzo → I raise", "youSay": "I raise.", "nativeSay": "I get up.", "why": "English uses PHRASAL VERBS (verb + particle) for many everyday actions. 'Get up' = alzarsi. 'Raise' means to lift something else. English has thousands of phrasal verbs that don't exist in Italian.", "tip": "Get up, sit down, turn on, turn off, pick up, put down — learn them as single units.", "parallels": [{"lang": "en", "text": "I get up at 7."}, {"lang": "it", "text": "Mi alzo alle sette."}, {"lang": "fr", "text": "Je me lève à sept heures."}], "examples": [{"correct": "I get up early.", "wrong": "I raise early.", "note": "Get up = alzarsi. Raise = alzare (transitive)."}, {"correct": "Turn on the light.", "wrong": "Open the light.", "note": "Turn on = accendere. Open = aprire."}]},
  {"id": "it-en-do-support", "direction": "it-en", "level": "a1", "category": "Questions", "title": "Parli inglese?", "youThink": "Parli inglese? → Speak you English?", "youSay": "Speak you English?", "nativeSay": "Do you speak English?", "why": "English requires DO/DID/DOES in questions and negatives with most verbs. Italian has no equivalent — you just raise intonation. 'Parli inglese?' cannot be translated word-for-word.", "tip": "Questions: Do/Does/Did + subject + verb. Negatives: subject + don't/doesn't/didn't + verb.", "parallels": [{"lang": "en", "text": "Do you speak English?"}, {"lang": "it", "text": "Parli inglese?"}, {"lang": "fr", "text": "Parles-tu anglais?"}], "examples": [{"correct": "Do you like pizza?", "wrong": "Like you pizza?", "note": "Do-support required."}, {"correct": "I don't understand.", "wrong": "I no understand.", "note": "Don't + verb."}]},
  {"id": "it-en-much-many", "direction": "it-en", "level": "a1", "category": "Quantifiers", "title": "Molti amici / Molta acqua", "youThink": "Molti amici → Much friends", "youSay": "Much friends.", "nativeSay": "Many friends.", "why": "English distinguishes between MANY (countable plural) and MUCH (uncountable). Italian uses MOLTI/MOLTE for countable and MOLTA for uncountable, but English has a stricter divide.", "tip": "Many + countable plural. Much + uncountable. A lot of + both.", "parallels": [{"lang": "en", "text": "Many friends. Much water."}, {"lang": "it", "text": "Molti amici. Molta acqua."}, {"lang": "fr", "text": "Beaucoup d'amis. Beaucoup d'eau."}], "examples": [{"correct": "I have many books.", "wrong": "I have much books.", "note": "Books = countable: many."}, {"correct": "I don't have much time.", "wrong": "I don't have many time.", "note": "Time = uncountable: much."}]},
  {"id": "it-en-get", "direction": "it-en", "level": "a2", "category": "Verbs", "title": "Ho capito / Ho ricevuto", "youThink": "Ho capito → I have understood", "youSay": "I have understood.", "nativeSay": "I get it. / I got it.", "why": "English GET is a magic verb with dozens of meanings: obtain, become, arrive, understand, receive, buy, catch. Italian uses different verbs for each meaning. 'Get' is incredibly common in spoken English.", "tip": "Get = capire, ricevere, diventare, arrivare, prendere, comprare. Context decides.", "parallels": [{"lang": "en", "text": "I get it. I got a letter. I got tired."}, {"lang": "it", "text": "Ho capito. Ho ricevuto una lettera. Mi sono stancato."}, {"lang": "fr", "text": "J'ai compris. J'ai reçu une lettre."}], "examples": [{"correct": "I got your message.", "wrong": "I became your message.", "note": "Got = received."}, {"correct": "I get tired easily.", "wrong": "I receive tired easily.", "note": "Get tired = become tired."}]},
  {"id": "it-en-used-to", "direction": "it-en", "level": "a2", "category": "Tenses", "title": "Andavo a scuola a piedi", "youThink": "Andavo a scuola a piedi → I went to school on foot", "youSay": "I went to school on foot.", "nativeSay": "I used to go to school on foot.", "why": "English USES 'used to' for past habits that no longer happen. The simple past just states a fact. 'I went to school on foot' could mean once or always. 'I used to go' specifically means it was a habit.", "tip": "Used to + verb = past habit. Didn't use to = negative past habit.", "parallels": [{"lang": "en", "text": "I used to go."}, {"lang": "it", "text": "Andavo."}, {"lang": "fr", "text": "J'allais. / J'avais l'habitude d'aller."}], "examples": [{"correct": "I used to live in Rome.", "wrong": "I lived in Rome.", "note": "'Used to' = past habit. 'Lived' = just a fact."}, {"correct": "Did you use to smoke?", "wrong": "Did you used to smoke?", "note": "Did + use to (not used to)."}]},
  {"id": "it-en-will-going", "direction": "it-en", "level": "a2", "category": "Tenses", "title": "Domani pioverà", "youThink": "Domani pioverà → Tomorrow it will to rain", "youSay": "Tomorrow it will to rain.", "nativeSay": "It's going to rain tomorrow. / It will rain tomorrow.", "why": "English has two main future forms: WILL (decision at moment of speaking, predictions) and GOING TO (plans, intentions, evidence). Italian uses the simple future or present tense for both.", "tip": "Decision now: I'll help you. Plan/evidence: It's going to rain. Prediction: It will rain.", "parallels": [{"lang": "en", "text": "It's going to rain. It will rain."}, {"lang": "it", "text": "Pioverà."}, {"lang": "fr", "text": "Il va pleuvoir. Il pleuvra."}], "examples": [{"correct": "I'll get it! (phone rings)", "wrong": "I'm going to get it! (instant decision)", "note": "Instant decision = will."}, {"correct": "Look at those clouds — it's going to rain.", "wrong": "Look at those clouds — it will rain.", "note": "Evidence = going to."}]},
  {"id": "it-en-past-simple-perfect", "direction": "it-en", "level": "a2", "category": "Tenses", "title": "Ho visto quel film", "youThink": "Ho visto quel film → I have seen that film", "youSay": "I have seen that film.", "nativeSay": "I saw that film. / I've seen that film.", "why": "English uses present perfect for experiences with no specific time. Past simple for completed actions at a specific time. Italian passato prossimo covers both. 'I saw' (specific time) vs 'I've seen' (experience).", "tip": "Past simple + time = completed. Present perfect = experience/result. I saw it yesterday. I've seen it before.", "parallels": [{"lang": "en", "text": "I saw it yesterday. I've seen it before."}, {"lang": "it", "text": "L'ho visto ieri. L'ho già visto."}, {"lang": "fr", "text": "Je l'ai vu hier. Je l'ai déjà vu."}], "examples": [{"correct": "I visited Paris last year.", "wrong": "I have visited Paris last year.", "note": "Last year = past simple."}, {"correct": "I've never been to Japan.", "wrong": "I never was in Japan.", "note": "Never + experience = present perfect."}]},
  {"id": "it-en-articles-zero", "direction": "it-en", "level": "a1", "category": "Articles", "title": "Amo la musica", "youThink": "Amo la musica → I love the music", "youSay": "I love the music.", "nativeSay": "I love music.", "why": "English drops the article with abstract nouns and general categories. Italian keeps it. 'Amo la musica' = I love music (no article in English). 'La' disappears in translation.", "tip": "General categories: no article. I love music. I hate violence. She studies English.", "parallels": [{"lang": "en", "text": "I love music."}, {"lang": "it", "text": "Amo la musica."}, {"lang": "fr", "text": "J'aime la musique."}], "examples": [{"correct": "I study English.", "wrong": "I study the English.", "note": "Languages: no article."}, {"correct": "Life is beautiful.", "wrong": "The life is beautiful.", "note": "Abstract nouns: no article."}]},
  {"id": "it-en-adjective-order", "direction": "it-en", "level": "a1", "category": "Word Order", "title": "Una casa grande e bella", "youThink": "Una casa grande e bella → A house big and beautiful", "youSay": "A house big and beautiful.", "nativeSay": "A beautiful big house.", "why": "English adjectives have a fixed order: opinion, size, age, shape, color, origin, material, purpose. Italian is more flexible. 'Bella casa grande' becomes 'beautiful big house' in English.", "tip": "OSASCOMP: Opinion, Size, Age, Shape, Color, Origin, Material, Purpose.", "parallels": [{"lang": "en", "text": "A beautiful big old Italian house."}, {"lang": "it", "text": "Una bella casa grande vecchia italiana."}, {"lang": "fr", "text": "Une belle grande vieille maison italienne."}], "examples": [{"correct": "A lovely little old car.", "wrong": "An old little lovely car.", "note": "Opinion → size → age."}, {"correct": "A red Italian leather bag.", "wrong": "An Italian leather red bag.", "note": "Color → origin → material."}]},
  {"id": "it-en-possessives-no-article", "direction": "it-en", "level": "a1", "category": "Possession", "title": "Il mio libro", "youThink": "Il mio libro → The my book", "youSay": "The my book.", "nativeSay": "My book.", "why": "English NEVER uses an article with possessive adjectives. 'My book,' not 'the my book.' Italian always uses the article: 'il mio libro.' Drop the article in English.", "tip": "No article with possessives. My, your, his, her, its, our, their.", "parallels": [{"lang": "en", "text": "My book."}, {"lang": "it", "text": "Il mio libro."}, {"lang": "fr", "text": "Mon livre."}], "examples": [{"correct": "My parents are here.", "wrong": "The my parents are here.", "note": "Never 'the my.'"}, {"correct": "Her house is big.", "wrong": "The her house is big.", "note": "No article before possessive."}]},
  {"id": "it-en-there-is", "direction": "it-en", "level": "a1", "category": "Existence", "title": "C'è un problema", "youThink": "C'è un problema → It is a problem", "youSay": "It is a problem.", "nativeSay": "There is a problem.", "why": "English uses THERE IS/THERE ARE for existence. 'It is' refers to a specific thing already mentioned. 'There is' introduces something new. Italian 'c'è' covers both, but in English, 'there is' is for existence.", "tip": "There is/are = existence. It is = identity. There is a problem. It is a big problem.", "parallels": [{"lang": "en", "text": "There is a problem."}, {"lang": "it", "text": "C'è un problema."}, {"lang": "fr", "text": "Il y a un problème."}], "examples": [{"correct": "There is a book on the table.", "wrong": "It is a book on the table.", "note": "Existence = there is."}, {"correct": "There are many people.", "wrong": "There is many people.", "note": "Plural = there are."}]},
  {"id": "it-en-it-there", "direction": "it-en", "level": "a1", "category": "Subjects", "title": "Piove / È tardi", "youThink": "Piove → Rains", "youSay": "Rains.", "nativeSay": "It rains. / It's raining.", "why": "English always needs a subject. Italian can drop it. Weather, time, and distance all use IT in English: it rains, it is late, it is far. Italian just says 'piove,' 'è tardi.'", "tip": "Weather: It rains. Time: It is late. Distance: It is far. Always use IT.", "parallels": [{"lang": "en", "text": "It is raining. It is late."}, {"lang": "it", "text": "Piove. È tardi."}, {"lang": "fr", "text": "Il pleut. Il est tard."}], "examples": [{"correct": "It is cold today.", "wrong": "Is cold today.", "note": "Always 'it' for weather."}, {"correct": "It is 5 o'clock.", "wrong": "Is 5 o'clock.", "note": "Always 'it' for time."}]},
  {"id": "it-en-relative-who", "direction": "it-en", "level": "a2", "category": "Clauses", "title": "L'uomo che ho visto", "youThink": "L'uomo che ho visto → The man which I saw", "youSay": "The man which I saw.", "nativeSay": "The man who/that I saw.", "why": "English uses WHO for people, WHICH for things, and THAT for both. Italian uses CHE for everything. Don't use 'which' for people in English.", "tip": "Who = people. Which = things. That = both. The man WHO/THAT I met.", "parallels": [{"lang": "en", "text": "The man who I saw."}, {"lang": "it", "text": "L'uomo che ho visto."}, {"lang": "fr", "text": "L'homme que j'ai vu."}], "examples": [{"correct": "The woman who called you.", "wrong": "The woman which called you.", "note": "People = who/that."}, {"correct": "The car that/which I bought.", "wrong": "The car who I bought.", "note": "Things = which/that."}]},
  {"id": "it-en-reported-speech", "direction": "it-en", "level": "b1", "category": "Speech", "title": "Ha detto che viene", "youThink": "Ha detto che viene → He said that he comes", "youSay": "He said that he comes.", "nativeSay": "He said that he would come. / He said that he was coming.", "why": "English REPORTED SPEECH shifts tenses back. Present becomes past. Will becomes would. Can becomes could. Italian often keeps the original tense in spoken language, but English requires backshift.", "tip": "Said + past tense. 'I will come' → He said he WOULD come. 'I am busy' → He said he WAS busy.", "parallels": [{"lang": "en", "text": "He said he would come."}, {"lang": "it", "text": "Ha detto che viene. (spoken Italian keeps present)"}, {"lang": "fr", "text": "Il a dit qu'il viendrait."}], "examples": [{"correct": "She said she was tired.", "wrong": "She said that she is tired.", "note": "Backshift: is → was."}, {"correct": "He told me he couldn't help.", "wrong": "He told me he can't help.", "note": "Backshift: can → could."}]},
  {"id": "it-en-conditionals", "direction": "it-en", "level": "a2", "category": "Conditionals", "title": "Se avessi soldi, comprerei...", "youThink": "Se avessi soldi, comprerei una macchina → If I have money, I buy a car", "youSay": "If I have money, I buy a car.", "nativeSay": "If I had money, I would buy a car.", "why": "English conditional 2 uses PAST SIMPLE in the if-clause and WOULD + verb in the main clause. Italian uses congiuntivo + conditional. Don't use present tense in English hypothetical conditionals.", "tip": "Hypothetical: If + past, would + verb. If I won, I would travel.", "parallels": [{"lang": "en", "text": "If I had money, I would buy a car."}, {"lang": "it", "text": "Se avessi soldi, comprerei una macchina."}, {"lang": "fr", "text": "Si j'avais de l'argent, j'achèterais une voiture."}], "examples": [{"correct": "If I were you, I would wait.", "wrong": "If I am you, I wait.", "note": "If I were = hypothetical."}, {"correct": "She would come if she could.", "wrong": "She comes if she can.", "note": "Would + past = hypothetical."}]},
  {"id": "it-en-can-may", "direction": "it-en", "level": "a2", "category": "Modals", "title": "Posso uscire?", "youThink": "Posso uscire? → Can I go out?", "youSay": "Can I go out? (to a teacher)", "nativeSay": "May I go out? / Can I go out?", "why": "English traditionally uses MAY for permission (more formal/polite) and CAN for ability. In modern English, CAN is accepted for both, but MAY is still more polite in formal situations. Italian uses POTERE for both.", "tip": "May = polite permission. Can = ability/informal permission. Could = past ability or polite request.", "parallels": [{"lang": "en", "text": "May I go out? Can you swim?"}, {"lang": "it", "text": "Posso uscire? Sai nuotare?"}, {"lang": "fr", "text": "Puis-je sortir? Sais-tu nager?"}], "examples": [{"correct": "May I use your phone? (formal)", "wrong": "Can I use your phone? (acceptable but less formal)", "note": "May = more polite."}, {"correct": "I can swim.", "wrong": "I may swim.", "note": "Can = ability."}]},
  {"id": "it-en-countable", "direction": "it-en", "level": "a1", "category": "Nouns", "title": "Un consiglio / dei consigli", "youThink": "Un consiglio → An advice", "youSay": "An advice.", "nativeSay": "A piece of advice. / Some advice.", "why": "English ADVICE is UNCOUNTABLE. You cannot say 'an advice' or 'advices.' Italian 'un consiglio' is countable. For uncountable nouns in English, use 'a piece of' or 'some.'", "tip": "Advice, information, news, furniture, luggage = uncountable. No plural, no a/an.", "parallels": [{"lang": "en", "text": "A piece of advice. Some information."}, {"lang": "it", "text": "Un consiglio. Delle informazioni."}, {"lang": "fr", "text": "Un conseil. Des informations."}], "examples": [{"correct": "Can you give me some advice?", "wrong": "Can you give me an advice?", "note": "Advice = uncountable."}, {"correct": "I have some good news.", "wrong": "I have a good news.", "note": "News = uncountable (no plural)."}]},
  {"id": "it-en-make-do", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Faccio la doccia / Faccio i compiti", "youThink": "Faccio i compiti → I make my homework", "youSay": "I make my homework.", "nativeSay": "I do my homework.", "why": "English uses DO for activities, tasks, and duties. MAKE for creating, constructing, or causing. Italian uses FARE for both. 'Do homework,' 'make a cake,' 'make a decision,' 'do business.'", "tip": "DO: homework, business, exercise, housework, someone a favor. MAKE: a cake, a decision, a mistake, a phone call, an effort.", "parallels": [{"lang": "en", "text": "Do homework. Make a cake."}, {"lang": "it", "text": "Fare i compiti. Fare una torta."}, {"lang": "fr", "text": "Faire mes devoirs. Faire un gâteau."}], "examples": [{"correct": "I need to do the shopping.", "wrong": "I need to make the shopping.", "note": "Do the shopping."}, {"correct": "She made a mistake.", "wrong": "She did a mistake.", "note": "Make a mistake."}]},
  {"id": "it-en-say-tell", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Dico / Dico a", "youThink": "Dico a Marco → I say to Marco", "youSay": "I say to Marco.", "nativeSay": "I tell Marco. / I said to Marco.", "why": "English SAY does not take an indirect object without TO. TELL takes an indirect object directly. 'I tell him' = 'Gli dico.' 'I say to him' = 'Gli dico.' But 'I say him' is wrong.", "tip": "Tell + person (no to). Say + to + person. Tell me. Say it to me.", "parallels": [{"lang": "en", "text": "Tell me. Say it to me."}, {"lang": "it", "text": "Dimmi. Dillo a me."}, {"lang": "fr", "text": "Dis-moi. Dis-le-moi."}], "examples": [{"correct": "Tell me the truth.", "wrong": "Say me the truth.", "note": "Tell + person."}, {"correct": "Say hello to your mother.", "wrong": "Tell hello to your mother.", "note": "Say + to + person."}]},
  {"id": "it-en-look-for", "direction": "it-en", "level": "a1", "category": "Phrasal Verbs", "title": "Cerco il mio telefono", "youThink": "Cerco il mio telefono → I look my phone", "youSay": "I look my phone.", "nativeSay": "I'm looking for my phone.", "why": "English LOOK needs a particle to mean 'search for.' 'Look' alone means 'direct your gaze.' 'Look for' = cercare. 'Look after' = prendersi cura di. 'Look like' = assomigliare a.", "tip": "Look for = search. Look after = take care of. Look like = resemble. Look up = search in reference.", "parallels": [{"lang": "en", "text": "I'm looking for my phone."}, {"lang": "it", "text": "Cerco il mio telefono."}, {"lang": "fr", "text": "Je cherche mon téléphone."}], "examples": [{"correct": "I look after my sister.", "wrong": "I look my sister.", "note": "Look after = take care of."}, {"correct": "You look like your father.", "wrong": "You look your father.", "note": "Look like = resemble."}]},
  {"id": "it-en-bring-take", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Porto il libro a Marco", "youThink": "Porto il libro a Marco → I carry the book to Marco", "youSay": "I carry the book to Marco.", "nativeSay": "I take the book to Marco. / I'll bring the book to Marco.", "why": "English BRING = movement toward the speaker/listener. TAKE = movement away. CARRY = holding while moving (regardless of direction). Italian 'portare' covers all three.", "tip": "Bring = toward. Take = away. Carry = hold while moving. Bring me the book. Take this to the kitchen.", "parallels": [{"lang": "en", "text": "Bring it here. Take it there."}, {"lang": "it", "text": "Portamelo qui. Portalo lì."}, {"lang": "fr", "text": "Apporte-le ici. Emmène-le là-bas."}], "examples": [{"correct": "Can you bring me some water?", "wrong": "Can you take me some water?", "note": "Bring = toward speaker."}, {"correct": "I'll take this letter to the post office.", "wrong": "I'll bring this letter to the post office.", "note": "Take = away from speaker."}]},
  {"id": "it-en-too-enough", "direction": "it-en", "level": "a1", "category": "Quantifiers", "title": "Troppo caro / Abbastanza buono", "youThink": "Troppo caro → Too much expensive", "youSay": "Too much expensive.", "nativeSay": "Too expensive.", "why": "English TOO goes directly before adjectives: too expensive, too hot, too difficult. 'Too much' goes before uncountable nouns: too much money. 'Much too' emphasizes: much too expensive.", "tip": "Too + adjective. Too much + uncountable noun. Much too + adjective (emphasis).", "parallels": [{"lang": "en", "text": "Too expensive. Too much money."}, {"lang": "it", "text": "Troppo caro. Troppi soldi."}, {"lang": "fr", "text": "Trop cher. Trop d'argent."}], "examples": [{"correct": "It's too cold.", "wrong": "It's too much cold.", "note": "Too + adjective."}, {"correct": "I have too much work.", "wrong": "I have too work.", "note": "Too much + uncountable noun."}]},
  {"id": "it-en-still-yet", "direction": "it-en", "level": "a1", "category": "Time", "title": "Non ho ancora mangiato", "youThink": "Non ho ancora mangiato → I don't have still eaten", "youSay": "I don't have still eaten.", "nativeSay": "I haven't eaten yet.", "why": "English YET goes at the END of negative sentences and questions. STILL goes in the middle of positive sentences. ALREADY goes in the middle. Italian uses ANCORA for all three positions but English separates them.", "tip": "Yet = end of negative/question. Still = middle (positive or negative). Already = middle (positive).", "parallels": [{"lang": "en", "text": "I haven't eaten yet. I still haven't eaten. I've already eaten."}, {"lang": "it", "text": "Non ho ancora mangiato."}, {"lang": "fr", "text": "Je n'ai pas encore mangé."}], "examples": [{"correct": "Have you finished yet?", "wrong": "Have you yet finished?", "note": "Yet at the end."}, {"correct": "I still don't understand.", "wrong": "I don't understand still.", "note": "Still in the middle."}]},
  {"id": "it-en-ever-never", "direction": "it-en", "level": "a1", "category": "Time", "title": "Non sono mai stato in Giappone", "youThink": "Non sono mai stato in Giappone → I never have been to Japan", "youSay": "I never have been to Japan.", "nativeSay": "I have never been to Japan.", "why": "English NEVER goes between HAVE and the past participle in present perfect sentences. 'I have never been' not 'I never have been.' Italian 'non sono mai stato' puts MAI after the auxiliary.", "tip": "Have + never/ever/always + past participle. I have never seen. Have you ever been?", "parallels": [{"lang": "en", "text": "I have never been to Japan."}, {"lang": "it", "text": "Non sono mai stato in Giappone."}, {"lang": "fr", "text": "Je ne suis jamais allé au Japon."}], "examples": [{"correct": "Have you ever tried sushi?", "wrong": "Do you ever have tried sushi?", "note": "Have + ever + participle."}, {"correct": "I have always wanted to visit Rome.", "wrong": "I always have wanted to visit Rome.", "note": "Have + always + participle."}]},
  {"id": "it-en-for-since", "direction": "it-en", "level": "a1", "category": "Time", "title": "Vivo qui da due anni", "youThink": "Vivo qui da due anni → I live here since two years", "youSay": "I live here since two years.", "nativeSay": "I have lived here for two years.", "why": "English uses FOR with durations (for two years) and SINCE with starting points (since 2020). Italian uses DA for both. Also, English uses present perfect for actions continuing from past to present. Italian uses present tense.", "tip": "For + duration. Since + starting point. I have lived here FOR five years. I have lived here SINCE 2019.", "parallels": [{"lang": "en", "text": "I have lived here for two years."}, {"lang": "it", "text": "Vivo qui da due anni."}, {"lang": "fr", "text": "J'habite ici depuis deux ans."}], "examples": [{"correct": "I have known him for a long time.", "wrong": "I know him since a long time.", "note": "For + duration."}, {"correct": "I have worked here since 2020.", "wrong": "I have worked here for 2020.", "note": "Since + starting point."}]},
  {"id": "it-en-travel-trip", "direction": "it-en", "level": "a1", "category": "Nouns", "title": "Faccio un viaggio", "youThink": "Faccio un viaggio → I make a travel", "youSay": "I make a travel.", "nativeSay": "I take a trip. / I'm going on a trip.", "why": "English TRAVEL is uncountable and a verb. TRIP is a countable noun for a specific journey. JOURNEY emphasizes the traveling itself. VOYAGE is long by sea/space. Italian 'viaggio' covers all of these.", "tip": "Travel = verb/uncountable noun. Trip = countable noun (short). Journey = the act of traveling. Take a trip. Go on a journey.", "parallels": [{"lang": "en", "text": "I take a trip. I travel a lot."}, {"lang": "it", "text": "Faccio un viaggio. Viaggio molto."}, {"lang": "fr", "text": "Je fais un voyage. Je voyage beaucoup."}], "examples": [{"correct": "I'm going on a trip to Paris.", "wrong": "I'm making a travel to Paris.", "note": "Take a trip / go on a trip."}, {"correct": "I love to travel.", "wrong": "I love to do travels.", "note": "Travel = verb/uncountable."}]},
  {"id": "it-en-job-work", "direction": "it-en", "level": "a1", "category": "Nouns", "title": "Ho un lavoro", "youThink": "Ho un lavoro → I have a work", "youSay": "I have a work.", "nativeSay": "I have a job. / I have work to do.", "why": "English JOB is countable (a job, two jobs). WORK is uncountable (no plural, no a/an). Italian 'lavoro' is both. 'I have a work' is wrong — say 'a job' for employment or 'work' for tasks.", "tip": "Job = countable (employment). Work = uncountable (tasks/labor). I have a job. I have work to do.", "parallels": [{"lang": "en", "text": "I have a job. I have work."}, {"lang": "it", "text": "Ho un lavoro. Ho del lavoro."}, {"lang": "fr", "text": "J'ai un travail. J'ai du travail."}], "examples": [{"correct": "I found a new job.", "wrong": "I found a new work.", "note": "Job = countable."}, {"correct": "I have too much work.", "wrong": "I have too many works.", "note": "Work = uncountable."}]},
  {"id": "it-en-house-home", "direction": "it-en", "level": "a1", "category": "Nouns", "title": "A casa mia", "youThink": "A casa mia → To my house", "youSay": "To my house.", "nativeSay": "Home. / At my place.", "why": "English HOUSE = the physical building. HOME = the place where you live (emotional/abstract). 'I'm going home' = not to a specific house, but to where you belong. Italian 'casa' covers both.", "tip": "Home = where you live/belong. House = the building. Go home (no to). At home.", "parallels": [{"lang": "en", "text": "I'm going home. I bought a house."}, {"lang": "it", "text": "Vado a casa. Ho comprato una casa."}, {"lang": "fr", "text": "Je rentre chez moi. J'ai acheté une maison."}], "examples": [{"correct": "I'll be home at 6.", "wrong": "I'll be to home at 6.", "note": "Go home (no preposition)."}, {"correct": "They have a beautiful house.", "wrong": "They have a beautiful home.", "note": "House = building. Home = emotional concept."}]},
  {"id": "it-en-client-customer", "direction": "it-en", "level": "a2", "category": "Nouns", "title": "Ho un cliente", "youThink": "Ho un cliente → I have a client", "youSay": "I have a client.", "nativeSay": "I have a client. / I have a customer.", "why": "English CLIENT = professional services (lawyer, consultant). CUSTOMER = retail/shops. Italian 'cliente' covers both. In English, using 'client' for a shop sounds overly formal.", "tip": "Client = professional services. Customer = shops/restaurants.", "parallels": [{"lang": "en", "text": "A lawyer has clients. A shop has customers."}, {"lang": "it", "text": "Un avvocato ha clienti. Un negozio ha clienti."}, {"lang": "fr", "text": "Un avocat a des clients. Un magasin a des clients."}], "examples": [{"correct": "The customer is always right.", "wrong": "The client is always right.", "note": "Customer = retail."}, {"correct": "My lawyer has many clients.", "wrong": "My lawyer has many customers.", "note": "Client = professional."}]},
  {"id": "it-en-lecture-lesson", "direction": "it-en", "level": "a1", "category": "Nouns", "title": "Ho una lezione", "youThink": "Ho una lezione → I have a lecture", "youSay": "I have a lecture.", "nativeSay": "I have a class. / I have a lesson.", "why": "English LECTURE = a formal talk by one person to many (university). LESSON = a teaching session with interaction. CLASS = the general term for a teaching session. Italian 'lezione' covers all three.", "tip": "Lecture = one-way formal talk. Lesson = interactive teaching. Class = general term.", "parallels": [{"lang": "en", "text": "I have a class. I attended a lecture."}, {"lang": "it", "text": "Ho una lezione. Ho seguito una lezione."}, {"lang": "fr", "text": "J'ai un cours. J'ai assisté à une conférence."}], "examples": [{"correct": "I have math class at 9.", "wrong": "I have a math lecture at 9.", "note": "Class = general."}, {"correct": "The professor gave an interesting lecture.", "wrong": "The professor gave an interesting lesson.", "note": "Lecture = formal talk."}]},
  {"id": "it-en-argument-discussion", "direction": "it-en", "level": "a2", "category": "Nouns", "title": "Abbiamo avuto una discussione", "youThink": "Abbiamo avuto una discussione → We had an argument", "youSay": "We had an argument.", "nativeSay": "We had a discussion. / We had an argument.", "why": "English ARGUMENT = a fight/disagreement (negative). DISCUSSION = a conversation about a topic (neutral). Italian 'discussione' can mean both, but in English the distinction is important.", "tip": "Discussion = neutral conversation. Argument = disagreement/fight. Debate = formal structured discussion.", "parallels": [{"lang": "en", "text": "We had a discussion. We had an argument."}, {"lang": "it", "text": "Abbiamo avuto una discussione."}, {"lang": "fr", "text": "Nous avons eu une discussion. Nous avons eu une dispute."}], "examples": [{"correct": "We had a long discussion about politics.", "wrong": "We had a long argument about politics.", "note": "Discussion = neutral. Argument = negative."}, {"correct": "They had a terrible argument.", "wrong": "They had a terrible discussion.", "note": "Argument = fight."}]},
  {"id": "it-en-sensible-sensitive", "direction": "it-en", "level": "a2", "category": "Adjectives", "title": "È una persona sensibile", "youThink": "È una persona sensibile → He is a sensible person", "youSay": "He is a sensible person.", "nativeSay": "He is a sensitive person.", "why": "English SENSITIVE = emotionally reactive, easily hurt. SENSIBLE = practical, reasonable. Italian 'sensibile' = sensitive (not sensible). 'Ragionevole' or 'pratico' = sensible.", "tip": "Sensitive = emotional. Sensible = practical. Don't confuse them!", "parallels": [{"lang": "en", "text": "He is sensitive. She is sensible."}, {"lang": "it", "text": "È sensibile. È ragionevole."}, {"lang": "fr", "text": "Il est sensible. Elle est sensée."}], "examples": [{"correct": "My skin is very sensitive.", "wrong": "My skin is very sensible.", "note": "Sensitive = reactive."}, {"correct": "That was a sensible decision.", "wrong": "That was a sensitive decision.", "note": "Sensible = practical/reasonable."}]},
  {"id": "it-en-convenient", "direction": "it-en", "level": "a2", "category": "Adjectives", "title": "È comodo prendere il treno", "youThink": "È comodo prendere il treno → It is convenient to take the train", "youSay": "It is convenient to take the train.", "nativeSay": "It is convenient to take the train.", "why": "Wait — 'convenient' DOES work here! But be careful: Italian 'conveniente' means cheap/good value, while English 'convenient' means easy/practical. 'Convenient' in English = comodo/pratico. 'Conveniente' in Italian = cheap.", "tip": "Convenient = easy/practical. Convenient for you? Good value = cheap/good price.", "parallels": [{"lang": "en", "text": "Convenient = easy. Good value = cheap."}, {"lang": "it", "text": "Comodo = convenient. Conveniente = good value."}, {"lang": "fr", "text": "Pratique = convenient. Bon marché = cheap."}], "examples": [{"correct": "Is 3pm convenient for you?", "wrong": "Is 3pm conveniente for you?", "note": "Convenient = comodo."}, {"correct": "This restaurant is very conveniente (Italian) = cheap.", "wrong": "This restaurant is very convenient = might mean easy to reach.", "note": "Conveniente ≠ convenient."}]},
  {"id": "it-en-pretend", "direction": "it-en", "level": "a2", "category": "Verbs", "title": "Finge di essere malato", "youThink": "Finge di essere malato → He pretends to be sick", "youSay": "He pretends to be sick.", "nativeSay": "He pretends to be sick.", "why": "English PRETEND = to act as if something is true. Italian 'fingere' = pretend. But Italian 'pretendere' = to demand/expect. Don't confuse them when translating back to Italian.", "tip": "Pretend = fingere. Pretendere (Italian) = to demand. These are false friends.", "parallels": [{"lang": "en", "text": "He pretends to be sick."}, {"lang": "it", "text": "Finge di essere malato."}, {"lang": "fr", "text": "Il fait semblant d'être malade."}], "examples": [{"correct": "Stop pretending!", "wrong": "Stop demanding! (if meaning pretend)", "note": "Pretend = fingere."}, {"correct": "He pretends he doesn't care.", "wrong": "He demands he doesn't care.", "note": "Pretend = act as if."}]},
  {"id": "it-en-actually", "direction": "it-en", "level": "a1", "category": "Adverbs", "title": "In realtà", "youThink": "In realtà → Actually", "youSay": "Actually.", "nativeSay": "Actually.", "why": "English ACTUALLY = in reality / surprisingly. Italian 'attualmente' = currently. 'In realtà' = actually. Don't confuse them.", "tip": "Actually = in realtà / in effetti. Currently = attualmente. At the moment = al momento.", "parallels": [{"lang": "en", "text": "Actually, I disagree."}, {"lang": "it", "text": "In realtà, non sono d'accordo."}, {"lang": "fr", "text": "En fait, je ne suis pas d'accord."}], "examples": [{"correct": "Actually, I've already finished.", "wrong": "Attualmente, ho già finito.", "note": "Actually = in realtà."}, {"correct": "Attualmente lavoro a Roma.", "wrong": "Actually I work in Rome.", "note": "Attualmente = currently."}]},
  {"id": "it-en-eventually", "direction": "it-en", "level": "a2", "category": "Adverbs", "title": "Alla fine / Finalmente", "youThink": "Alla fine → Eventually", "youSay": "Eventually.", "nativeSay": "Eventually. / Finally.", "why": "English EVENTUALLY = after a long time / in the end. Italian 'eventualmente' = possibly / if necessary. 'Alla fine' or 'finalmente' = eventually/finally.", "tip": "Eventually = alla fine / dopo un po'. Eventually ≠ eventualmente (which = possibly).", "parallels": [{"lang": "en", "text": "Eventually, he agreed."}, {"lang": "it", "text": "Alla fine ha accettato."}, {"lang": "fr", "text": "Finalement, il a accepté."}], "examples": [{"correct": "Eventually, I found the key.", "wrong": "Eventualmente, ho trovato la chiave.", "note": "Eventually = alla fine."}, {"correct": "Eventualmente possiamo rimandare.", "wrong": "Eventually we can postpone.", "note": "Eventualmente = possibly/if need be."}]},
  {"id": "it-en-raise-grow", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Cresco / Alzo", "youThink": "Cresco → I raise", "youSay": "I raise.", "nativeSay": "I grow.", "why": "English GROW = become bigger (intransitive). RAISE = make something bigger (transitive). Italian 'crescere' = grow. 'Alzare' = raise/lift. 'Crescere' is intransitive — you don't 'raise' yourself, you GROW.", "tip": "Grow = intransitive (I grow). Raise = transitive (I raise my hand).", "parallels": [{"lang": "en", "text": "I grow. I raise my hand."}, {"lang": "it", "text": "Cresco. Alzo la mano."}, {"lang": "fr", "text": "Je grandis. Je lève la main."}], "examples": [{"correct": "Children grow quickly.", "wrong": "Children raise quickly.", "note": "Grow = intransitive."}, {"correct": "Please raise your hand.", "wrong": "Please grow your hand.", "note": "Raise = transitive."}]},
  {"id": "it-en-watch-look-see", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Guardo / Vedo", "youThink": "Guardo la TV → I see the TV", "youSay": "I see the TV.", "nativeSay": "I watch TV.", "why": "English SEE = passive perception (accidental). LOOK = direct attention (active). WATCH = look at something moving/ongoing. Italian 'vedere' covers see and watch. 'Guardare' covers look and watch.", "tip": "See = perceive. Look = direct attention. Watch = observe ongoing activity. Watch TV. Look at me. I see a bird.", "parallels": [{"lang": "en", "text": "I watch TV. Look at me! I see a bird."}, {"lang": "it", "text": "Guardo la TV. Guardami! Vedo un uccello."}, {"lang": "fr", "text": "Je regarde la télé. Regarde-moi! Je vois un oiseau."}], "examples": [{"correct": "I watch football every Sunday.", "wrong": "I see football every Sunday.", "note": "Watch = ongoing activity."}, {"correct": "Look at that beautiful sunset!", "wrong": "See that beautiful sunset!", "note": "Look = direct attention."}]},
  {"id": "it-en-hear-listen", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Ascolto / Sento", "youThink": "Ascolto la musica → I hear the music", "youSay": "I hear the music.", "nativeSay": "I listen to the music.", "why": "English HEAR = passive perception (sound reaches your ears). LISTEN = active attention. Italian 'sentire' covers both hear and feel. 'Ascoltare' = listen. But in English, you must add TO after listen: 'listen TO music.'", "tip": "Hear = accidental. Listen to = intentional. Listen TO (always with TO).", "parallels": [{"lang": "en", "text": "I hear a noise. I listen to music."}, {"lang": "it", "text": "Sento un rumore. Ascolto la musica."}, {"lang": "fr", "text": "J'entends un bruit. J'écoute de la musique."}], "examples": [{"correct": "I listen to podcasts.", "wrong": "I listen podcasts.", "note": "Listen TO + object."}, {"correct": "Did you hear that?", "wrong": "Did you listen that?", "note": "Hear = perceive. Listen = intentional."}]},
  {"id": "it-en-fun-funny", "direction": "it-en", "level": "a1", "category": "Adjectives", "title": "È divertente", "youThink": "È divertente → He is funny", "youSay": "He is funny.", "nativeSay": "He is funny. / It is fun.", "why": "English FUNNY = makes you laugh (comical). FUN = enjoyable. Italian 'divertente' covers both, but in English, calling a serious activity 'funny' suggests it's ridiculous, not enjoyable.", "tip": "Funny = comical/laughable. Fun = enjoyable. The party was fun. The comedian was funny.", "parallels": [{"lang": "en", "text": "It was fun. He is funny."}, {"lang": "it", "text": "È stato divertente. È divertente."}, {"lang": "fr", "text": "C'était amusant. Il est drôle."}], "examples": [{"correct": "Swimming is fun.", "wrong": "Swimming is funny.", "note": "Fun = enjoyable. Funny = comical."}, {"correct": "His jokes are really funny.", "wrong": "His jokes are really fun.", "note": "Funny = comical."}]},
  {"id": "it-en-excited-exciting", "direction": "it-en", "level": "a1", "category": "Adjectives", "title": "Sono emozionato / È emozionante", "youThink": "Sono emozionato → I am exciting", "youSay": "I am exciting.", "nativeSay": "I am excited.", "why": "English -ED adjectives describe feelings (I am excited). -ING adjectives describe things that cause feelings (The movie is exciting). Italian 'emozionato' can be both, but English separates them strictly.", "tip": "-ED = feeling (I am bored). -ING = causing feeling (The book is boring).", "parallels": [{"lang": "en", "text": "I am excited. The game is exciting."}, {"lang": "it", "text": "Sono emozionato. La partita è emozionante."}, {"lang": "fr", "text": "Je suis excité. Le match est passionnant."}], "examples": [{"correct": "I am bored.", "wrong": "I am boring.", "note": "Bored = feeling. Boring = causing boredom."}, {"correct": "This class is interesting.", "wrong": "This class is interested.", "note": "Interesting = causing interest. Interested = feeling interest."}]},
  {"id": "it-en-some-any", "direction": "it-en", "level": "a1", "category": "Quantifiers", "title": "Ho qualche domanda / Non ho domande", "youThink": "Non ho domande → I don't have some questions", "youSay": "I don't have some questions.", "nativeSay": "I don't have any questions.", "why": "English uses SOME in positive sentences and ANY in negatives and questions. Italian 'qualche' and 'alcuni' don't follow this rule. In negative English sentences, always use ANY, not SOME.", "tip": "Some = positive. Any = negative and question. I have some. I don't have any. Do you have any?", "parallels": [{"lang": "en", "text": "I have some time. I don't have any time."}, {"lang": "it", "text": "Ho del tempo. Non ho tempo."}, {"lang": "fr", "text": "J'ai du temps. Je n'ai pas de temps."}], "examples": [{"correct": "Do you have any money?", "wrong": "Do you have some money?", "note": "Questions = any (when unsure)."}, {"correct": "I don't have any friends here.", "wrong": "I don't have some friends here.", "note": "Negatives = any."}]},
  {"id": "it-en-borrow-lend", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Mi presti i soldi?", "youThink": "Mi presti i soldi? → Can you borrow me some money?", "youSay": "Can you borrow me some money?", "nativeSay": "Can you lend me some money?", "why": "English BORROW = take something temporarily (from someone). LEND = give something temporarily (to someone). Italian 'prestare' covers both directions. 'Borrow' cannot take a person as indirect object.", "tip": "Borrow FROM. Lend TO. Can I borrow your pen? Can you lend me your pen?", "parallels": [{"lang": "en", "text": "Can you lend me some money?"}, {"lang": "it", "text": "Mi presti dei soldi?"}, {"lang": "fr", "text": "Peux-tu me prêter de l'argent?"}], "examples": [{"correct": "I borrowed a book from the library.", "wrong": "I lent a book from the library.", "note": "Borrow from = take."}, {"correct": "Can you lend me your car?", "wrong": "Can you borrow me your car?", "note": "Lend to = give temporarily."}]},
  {"id": "it-en-win-earn", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Guadagno / Vinco", "youThink": "Guadagno → I win money", "youSay": "I win money.", "nativeSay": "I earn money.", "why": "English WIN = victory in competition (win a game, win the lottery). EARN = receive money for work. Italian 'vincere' = win. 'Guadagnare' = earn. Don't confuse them.", "tip": "Win = competition/victory. Earn = work/salary. Gain = increase/acquire.", "parallels": [{"lang": "en", "text": "I earn money. I won the match."}, {"lang": "it", "text": "Guadagno soldi. Ho vinto la partita."}, {"lang": "fr", "text": "Je gagne de l'argent. J'ai gagné le match."}], "examples": [{"correct": "I earn 3000 euros a month.", "wrong": "I win 3000 euros a month.", "note": "Earn = salary."}, {"correct": "Italy won the World Cup.", "wrong": "Italy earned the World Cup.", "note": "Win = victory."}]},
  {"id": "it-en-meet-know", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Conosco Marco", "youThink": "Conosco Marco → I know Marco", "youSay": "I know Marco.", "nativeSay": "I know Marco.", "why": "English KNOW covers both 'conoscere' (be acquainted with) and 'sapere' (have knowledge). But MEET means 'fare la conoscenza di' for the first time. 'Nice to meet you' = first encounter. 'I know him' = already acquainted.", "tip": "Meet = first encounter. Know = be acquainted with. Get to know = gradually become acquainted.", "parallels": [{"lang": "en", "text": "Nice to meet you. I know him well."}, {"lang": "it", "text": "Piacere di conoscerti. Lo conosco bene."}, {"lang": "fr", "text": "Enchanté(e). Je le connais bien."}], "examples": [{"correct": "I met her last year.", "wrong": "I knew her last year.", "note": "Met = first encounter."}, {"correct": "I've known him for ten years.", "wrong": "I've met him for ten years.", "note": "Known = ongoing acquaintance."}]},
  {"id": "it-en-spend-pass", "direction": "it-en", "level": "a1", "category": "Verbs", "title": "Passo il tempo / Spendo soldi", "youThink": "Passo il tempo → I spend the time", "youSay": "I spend the time.", "nativeSay": "I spend time. / I pass the time.", "why": "English SPEND TIME = use time doing something. PASS TIME = fill empty time. Italian 'passare il tempo' covers both, but 'spend time' is more common in English for intentional use of time.", "tip": "Spend time = intentional use. Pass time = fill empty time. Spend money = pagare.", "parallels": [{"lang": "en", "text": "I spend time with family. I pass time reading."}, {"lang": "it", "text": "Passo tempo con la famiglia."}, {"lang": "fr", "text": "Je passe du temps avec ma famille."}], "examples": [{"correct": "I spend two hours a day studying.", "wrong": "I pass two hours a day studying.", "note": "Spend time = intentional."}, {"correct": "How do you pass the time on trains?", "wrong": "How do you spend the time on trains?", "note": "Pass time = fill empty time."}]},
  {"id": "it-en-realize", "direction": "it-en", "level": "a2", "category": "Verbs", "title": "Mi sono reso conto", "youThink": "Mi sono reso conto → I realized", "youSay": "I realized.", "nativeSay": "I realized.", "why": "English REALIZE = become aware. Italian 'realizzare' = achieve/make real. 'Rendersi conto' = realize. These are false friends going both directions.", "tip": "Realize (English) = rendersi conto / capire. Realizzare (Italian) = achieve.", "parallels": [{"lang": "en", "text": "I realized I was wrong."}, {"lang": "it", "text": "Mi sono reso conto di aver torto."}, {"lang": "fr", "text": "Je me suis rendu compte que j'avais tort."}], "examples": [{"correct": "I realized it was too late.", "wrong": "I realized my dream (if meaning became aware)", "note": "Realize = become aware."}, {"correct": "I achieved my dream.", "wrong": "I realized my dream.", "note": "Achieve = realizzare. Realize = rendersi conto."}]},
  {"id": "it-en-fabric", "direction": "it-en", "level": "a2", "category": "Nouns", "title": "Il tessuto", "youThink": "Il tessuto → The fabric", "youSay": "The fabric.", "nativeSay": "The fabric.", "why": "English FABRIC = cloth/material. Italian 'fabbrica' = factory. 'Tessuto' = fabric. These are false friends across both directions.", "tip": "Fabric = tessuto. Factory = fabbrica. Fabric (English) ≠ fabbrica (Italian).", "parallels": [{"lang": "en", "text": "The fabric is soft."}, {"lang": "it", "text": "Il tessuto è morbido."}, {"lang": "fr", "text": "Le tissu est doux."}], "examples": [{"correct": "This fabric is expensive.", "wrong": "This fabbrica is expensive.", "note": "Fabric = tessuto."}, {"correct": "The factory is closed.", "wrong": "The fabric is closed.", "note": "Factory = fabbrica."}]},
  {"id": "it-en-parents", "direction": "it-en", "level": "a1", "category": "Nouns", "title": "I miei genitori", "youThink": "I miei genitori → My parents", "youSay": "My parents.", "nativeSay": "My parents.", "why": "English PARENTS = mother and father. PARENTI (Italian) = relatives. These are false friends. Italian 'genitori' = parents.", "tip": "Parents = genitori. Relatives = parenti. Parenti (Italian) ≠ parents (English).", "parallels": [{"lang": "en", "text": "My parents live in Rome."}, {"lang": "it", "text": "I miei genitori vivono a Roma."}, {"lang": "fr", "text": "Mes parents vivent à Rome."}], "examples": [{"correct": "I have many relatives in Sicily.", "wrong": "I have many parents in Sicily.", "note": "Relatives = parenti."}, {"correct": "My parents are coming to visit.", "wrong": "My parenti are coming to visit.", "note": "Parents = genitori."}]},
  {"id": "it-en-magazine", "direction": "it-en", "level": "a1", "category": "Nouns", "title": "Una rivista", "youThink": "Una rivista → A magazine", "youSay": "A magazine.", "nativeSay": "A magazine.", "why": "English MAGAZINE = rivista. Italian 'magazzino' = warehouse. These are false friends. Italian 'magazine' is not commonly used; 'rivista' is the standard word.", "tip": "Magazine = rivista. Warehouse = magazzino. Magazine (English) ≠ magazzino (Italian).", "parallels": [{"lang": "en", "text": "I read a magazine."}, {"lang": "it", "text": "Leggo una rivista."}, {"lang": "fr", "text": "Je lis un magazine."}], "examples": [{"correct": "I bought a fashion magazine.", "wrong": "I bought a fashion magazzino.", "note": "Magazine = rivista."}, {"correct": "The warehouse is full.", "wrong": "The magazine is full.", "note": "Warehouse = magazzino."}]},
  {"id": "it-en-patent", "direction": "it-en", "level": "a2", "category": "Nouns", "title": "Un brevetto", "youThink": "Un brevetto → A patent", "youSay": "A patent.", "nativeSay": "A patent.", "why": "English PATENT = brevetto. Italian 'patente' = driver's license. These are false friends going both directions.", "tip": "Patent = brevetto. Driver's license = patente. Patent (English) ≠ patente (Italian).", "parallels": [{"lang": "en", "text": "He got a patent for his invention."}, {"lang": "it", "text": "Ha ottenuto un brevetto per la sua invenzione."}, {"lang": "fr", "text": "Il a obtenu un brevet pour son invention."}], "examples": [{"correct": "I need to renew my driver's license.", "wrong": "I need to renew my patent.", "note": "Driver's license = patente."}, {"correct": "The patent expires next year.", "wrong": "The patente expires next year.", "note": "Patent = brevetto."}]},
  {"id": "it-en-moral", "direction": "it-en", "level": "a2", "category": "Nouns", "title": "La morale della storia", "youThink": "La morale della storia → The moral of the story", "youSay": "The moral of the story.", "nativeSay": "The moral of the story.", "why": "English MORAL = ethical lesson. Italian 'la morale' = moral lesson. But 'il morale' = mood/spirits. Gender matters in Italian.", "tip": "Moral = morale (lesson). Mood = morale (spirits). In English, moral = lesson. Morale = spirits.", "parallels": [{"lang": "en", "text": "The moral of the story."}, {"lang": "it", "text": "La morale della storia."}, {"lang": "fr", "text": "La morale de l'histoire."}], "examples": [{"correct": "The moral is: don't lie.", "wrong": "The morale is: don't lie.", "note": "Moral = lesson. Morale = spirits."}, {"correct": "Team morale is high.", "wrong": "Team moral is high.", "note": "Morale = spirits."}]},
  {"id": "it-en-grave", "direction": "it-en", "level": "a2", "category": "Adjectives", "title": "Una situazione grave", "youThink": "Una situazione grave → A grave situation", "youSay": "A grave situation.", "nativeSay": "A grave situation. / A serious situation.", "why": "English GRAVE = serious/severe (like Italian). But also = burial place. Italian 'grave' = serious. 'Tomba' = burial place. Context matters.", "tip": "Grave = serious (Italian and English). Grave = burial place (English only).", "parallels": [{"lang": "en", "text": "A grave situation."}, {"lang": "it", "text": "Una situazione grave."}, {"lang": "fr", "text": "Une situation grave."}], "examples": [{"correct": "This is a grave problem.", "wrong": "This is a tomba problem.", "note": "Grave = serious."}, {"correct": "The grave is in the cemetery.", "wrong": "The grave is in the cemetery.", "note": "In English, grave = burial place too."}]},
  {"id": "it-en-terrible", "direction": "it-en", "level": "a1", "category": "Adjectives", "title": "Terribile", "youThink": "Terribile → Terrible", "youSay": "Terrible.", "nativeSay": "Terrible. / Amazing (colloquial).", "why": "English TERRIBLE = very bad. Italian 'terribile' = terrible, but colloquially can also mean amazing/incredible. Context and tone matter.", "tip": "Terrible = very bad. Terribile (Italian colloquial) = incredible/amazing.", "parallels": [{"lang": "en", "text": "The weather is terrible."}, {"lang": "it", "text": "Il tempo è terribile."}, {"lang": "fr", "text": "Le temps est terrible."}], "examples": [{"correct": "The service was terrible.", "wrong": "The service was terribile.", "note": "Terrible (English spelling)."}, {"correct": "Ha una voce terribile! (compliment in Italian)", "wrong": "He has a terrible voice! (insult in English)", "note": "Terribile can be positive in Italian colloquial speech."}]},
  {"id": "it-en-resume", "direction": "it-en", "level": "a2", "category": "Nouns", "title": "Il mio curriculum", "youThink": "Il mio curriculum → My resume", "youSay": "My resume.", "nativeSay": "My resume. / My CV.", "why": "English RESUME = CV (American). CV = academic resume. Italian 'curriculum' = resume/CV. 'Riassumere' = to summarize. Don't confuse them.", "tip": "Resume = CV. Curriculum (Italian) = resume. Riassumere = to summarize.", "parallels": [{"lang": "en", "text": "I sent my resume."}, {"lang": "it", "text": "Ho inviato il mio curriculum."}, {"lang": "fr", "text": "J'ai envoyé mon CV."}], "examples": [{"correct": "Please send me your resume.", "wrong": "Please send me your riassunto.", "note": "Resume = curriculum."}, {"correct": "To summarize...", "wrong": "To resume...", "note": "Summarize = riassumere. Resume = CV."}]},
  {"id": "it-en-actually-currently", "direction": "it-en", "level": "a1", "category": "Adverbs", "title": "Attualmente", "youThink": "Attualmente → Actually", "youSay": "Actually.", "nativeSay": "Currently.", "why": "Italian 'attualmente' = currently/at present. English ACTUALLY = in reality/in fact. These are false friends. 'Actually' in English often introduces a surprising fact or correction.", "tip": "Actually = in realtà / in effetti. Currently = attualmente. At the moment = al momento.", "parallels": [{"lang": "en", "text": "Currently, I work in Rome. Actually, I disagree."}, {"lang": "it", "text": "Attualmente lavoro a Roma. In realtà, non sono d'accordo."}, {"lang": "fr", "text": "Actuellement, je travaille à Rome. En fait, je ne suis pas d'accord."}], "examples": [{"correct": "Currently, I live in Milan.", "wrong": "Actually, I live in Milan.", "note": "Currently = attualmente."}, {"correct": "Actually, I've already finished.", "wrong": "Attualmente, ho già finito.", "note": "Actually = in realtà."}]},
  {"id": "it-en-education", "direction": "it-en", "level": "a2", "category": "Nouns", "title": "L'educazione", "youThink": "L'educazione → Education", "youSay": "Education.", "nativeSay": "Manners / Upbringing.", "why": "Italian 'educazione' = manners/polite behavior/upbringing. English EDUCATION = schooling/learning. Italian 'istruzione' = education. 'Educazione' ≠ education.", "tip": "Education = istruzione. Manners/upbringing = educazione. Good manners = buona educazione.", "parallels": [{"lang": "en", "text": "He has good manners. She has a good education."}, {"lang": "it", "text": "Ha una buona educazione. Ha una buona istruzione."}, {"lang": "fr", "text": "Il a de bonnes manières. Elle a une bonne éducation."}], "examples": [{"correct": "His parents taught him good manners.", "wrong": "His parents taught him good education.", "note": "Manners = educazione."}, {"correct": "She has a university education.", "wrong": "She has a university educazione.", "note": "Education = istruzione."}]},
  {"id": "it-en-largo", "direction": "it-en", "level": "a1", "category": "Adjectives", "title": "Largo", "youThink": "Largo → Large", "youSay": "Large.", "nativeSay": "Wide.", "why": "Italian 'largo' = wide/broad. English LARGE = big in general. 'Largo' in Italian is the opposite of 'stretto' (narrow), not the opposite of 'small.'", "tip": "Largo = wide. Grande = large/big. Stretto = narrow.", "parallels": [{"lang": "en", "text": "The road is wide. The shirt is large."}, {"lang": "it", "text": "La strada è larga. La camicia è grande."}, {"lang": "fr", "text": "La route est large. La chemise est grande."}], "examples": [{"correct": "The river is very wide.", "wrong": "The river is very large.", "note": "Wide = largo."}, {"correct": "I need a large shirt.", "wrong": "I need a wide shirt.", "note": "Large = grande."}]},
  {"id": "it-en-casino", "direction": "it-en", "level": "a2", "category": "Nouns", "title": "Che casino!", "youThink": "Che casino! → What a casino!", "youSay": "What a casino!", "nativeSay": "What a mess!", "why": "Italian 'casino' (no accent) = mess/chaos (colloquial). 'Casinò' (with accent) = gambling house. English CASINO = gambling house only. 'Che casino!' in Italian has nothing to do with gambling.", "tip": "Casino (Italian) = mess. Casinò = gambling house. Casino (English) = gambling house.", "parallels": [{"lang": "en", "text": "What a mess!"}, {"lang": "it", "text": "Che casino!"}, {"lang": "fr", "text": "Quel bordel!"}], "examples": [{"correct": "Your room is a mess!", "wrong": "Your room is a casino!", "note": "Mess = casino (Italian)."}, {"correct": "Let's go to the casino.", "wrong": "Let's go to the casino (if in Italy, might be understood as gambling house).", "note": "Casinò = gambling house."}]},
  {"id": "it-en-camera", "direction": "it-en", "level": "a1", "category": "Nouns", "title": "Una macchina fotografica", "youThink": "Una macchina fotografica → A camera", "youSay": "A camera.", "nativeSay": "A camera.", "why": "English CAMERA = macchina fotografica. Italian 'camera' = room/bedroom. These are false friends across both directions.", "tip": "Camera (English) = macchina fotografica. Camera (Italian) = room. Don't confuse them!", "parallels": [{"lang": "en", "text": "I bought a camera."}, {"lang": "it", "text": "Ho comprato una macchina fotografica."}, {"lang": "fr", "text": "J'ai acheté un appareil photo."}], "examples": [{"correct": "I reserved a hotel room.", "wrong": "I reserved a hotel camera.", "note": "Room = camera (Italian)."}, {"correct": "She takes photos with her camera.", "wrong": "She takes photos with her room.", "note": "Camera = macchina fotografica."}]},
  {"id": "it-en-fattoria", "direction": "it-en", "level": "a1", "category": "Nouns", "title": "Una fattoria", "youThink": "Una fattoria → A factory", "youSay": "A factory.", "nativeSay": "A farm.", "why": "Italian 'fattoria' = farm. Italian 'fabbrica' = factory. English FACTORY = fabbrica. FARM = fattoria. Don't confuse them.", "tip": "Fattoria = farm. Fabbrica = factory. Factory (English) = fabbrica. Farm (English) = fattoria.", "parallels": [{"lang": "en", "text": "I live on a farm."}, {"lang": "it", "text": "Vivo in una fattoria."}, {"lang": "fr", "text": "Je vis dans une ferme."}], "examples": [{"correct": "The factory produces cars.", "wrong": "The fattoria produces cars.", "note": "Factory = fabbrica."}, {"correct": "The farm has many animals.", "wrong": "The fabbrica has many animals.", "note": "Farm = fattoria."}]},
]

print(f"New en-it lessons: {len(new_en_it)}")
print(f"New it-en lessons: {len(new_it_en)}")

# Read current file lines
with open('src/data/think-like.ts', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find insertion points
en_it_close_idx = None
it_en_close_idx = None
for i, line in enumerate(lines):
    if line.strip() == '];' and en_it_close_idx is None and i > 20:
        # First ]; after thinkLikeEnIt start
        en_it_close_idx = i
    elif line.strip() == '];' and en_it_close_idx is not None and it_en_close_idx is None and i > en_it_close_idx + 10:
        it_en_close_idx = i
        break

print(f"en_it_close at line {en_it_close_idx + 1}: {lines[en_it_close_idx].strip()}")
print(f"it_en_close at line {it_en_close_idx + 1}: {lines[it_en_close_idx].strip()}")

# Helper to format a lesson
def fmt_lesson(l):
    out = ["  {\n"]
    out.append(f'    id: "{l["id"]}",\n')
    out.append(f'    direction: "{l["direction"]}",\n')
    out.append(f'    level: "{l["level"]}",\n')
    out.append(f'    category: "{l["category"]}",\n')
    out.append(f'    title: "{l["title"]}",\n')
    out.append(f'    youThink: "{l["youThink"]}",\n')
    out.append(f'    youSay: "{l["youSay"]}",\n')
    out.append(f'    nativeSay: "{l["nativeSay"]}",\n')
    out.append(f'    why: "{l["why"]}",\n')
    out.append(f'    tip: "{l["tip"]}",\n')
    out.append("    parallels: [\n")
    for p in l["parallels"]:
        out.append(f'      {{ lang: "{p["lang"]}", text: "{p["text"]}" }},\n')
    out.append("    ],\n")
    out.append("    examples: [\n")
    for e in l["examples"]:
        note = f', note: "{e.get("note", "")}"' if e.get("note") else ""
        out.append(f'      {{ correct: "{e["correct"]}", wrong: "{e["wrong"]}"{note} }},\n')
    out.append("    ],\n")
    out.append("  },\n")
    return "".join(out)

# Build new lesson blocks
en_it_block = "".join([fmt_lesson(l) for l in new_en_it])
it_en_block = "".join([fmt_lesson(l) for l in new_it_en])

# Insert
new_lines = lines[:en_it_close_idx] + [en_it_block] + lines[en_it_close_idx:it_en_close_idx] + [it_en_block] + lines[it_en_close_idx:]

with open('src/data/think-like.ts', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print("Merged successfully into src/data/think-like.ts")

# Count
import re
with open('src/data/think-like.ts', 'r', encoding='utf-8') as f:
    content = f.read()
for direction in ['en-it', 'en-fr', 'en-es', 'it-en', 'fr-en', 'es-en']:
    count = len(re.findall(rf'direction: [\'\"]{direction}[\'\"]', content))
    print(f"  {direction}: {count} lessons")
