// AUTO-GENERATED by scripts/generate-zone-conversations.py
// DO NOT EDIT MANUALLY — re-run the script instead.
//
// Translation: Helsinki-NLP/opus-mt-en-it (CC-BY 4.0)
// English source: original templates (proprietary, you own them)
//
// To use: merge these entries into src/data/zone-stories.ts

export const generatedZoneStories: Record<string, any> = {
  "fontana-piazza_a2": {
    zoneId: "fontana-piazza",
    zoneName: "The Fountain",
    level: "a2",
    exchanges: [
      { speaker: "Tu", it: "Ciao, come stai oggi?", en: "Hi! How are you today?" },
      { speaker: "Amico", it: "Sto bene, grazie.", en: "I am well, thank you. And you?" },
      { speaker: "Tu", it: "Sono un po' stanca, ho lavorato tutta la mattina.", en: "I am a little tired. I was working all morning." },
      { speaker: "Amico", it: "Hai tempo per restare qui per un momento?", en: "That is hard! Do you have time to stay here for a moment?" },
      { speaker: "Tu", it: "Si', ho dieci minuti, l'acqua in questa fontana e' bellissima.", en: "Yes, I have ten minutes. The water in this fountain is beautiful." },
      { speaker: "Amico", it: "Vengo qui tutti i giorni, mi fa sentire calmo.", en: "It is. I come here every day. It makes me feel calm." },
      { speaker: "Tu", it: "Voglio farti un piccolo regalo... qui, un po' di frutta fresca.", en: "I want to give you a small gift. Here, some fresh fruit." },
      { speaker: "Amico", it: "E' molto gentile da parte tua, ci sediamo?", en: "Thank you! That is very kind. Shall we sit?" },
      { speaker: "Tu", it: "Si', sediamoci e parliamo, ho molte cose da dirti.", en: "Yes, let us sit and talk. I have many things to tell you." },
      { speaker: "Amico", it: "Voglio parlarvi del mio viaggio a Roma.", en: "Me too. I want to tell you about my trip to Rome." },
    ]
  },
  "bar-piazza_a2": {
    zoneId: "bar-piazza",
    zoneName: "The Bar",
    level: "a2",
    exchanges: [
      { speaker: "Barista", it: "Buongiorno, cosa vuole bere?", en: "Good morning! What do you want to drink?" },
      { speaker: "Tu", it: "Voglio un caffe' e un croissant, per favore.", en: "I want a coffee and a croissant, please." },
      { speaker: "Barista", it: "Vuoi che venga qui o che te lo porti via?", en: "Do you want it here or to take away?" },
      { speaker: "Tu", it: "Posso avere anche un bicchiere d'acqua?", en: "Here, please. Can I also have a glass of water?" },
      { speaker: "Barista", it: "Devi provare anche la nostra nuova torta dolce.", en: "Of course. You must try our new sweet cake too." },
      { speaker: "Tu", it: "Non dovrei, ma... sì, ne prendo un pezzetto.", en: "I should not, but... yes, I will take a small piece." },
      { speaker: "Barista", it: "Ottima scelta, dove vuoi mettere la borsa?", en: "Excellent choice. Where do you want to put your bag?" },
      { speaker: "Tu", it: "Lo metto qui, sotto la sedia.", en: "I will put it here, under the chair. How much is everything?" },
      { speaker: "Barista", it: "Hai bisogno di una ricevuta?", en: "Five euros. Do you need a receipt?" },
      { speaker: "Tu", it: "No, grazie, tieni il resto.", en: "No, thank you. Keep the change." },
    ]
  },
  "fermata-piazza_a2": {
    zoneId: "fermata-piazza",
    zoneName: "Bus Stop",
    level: "a2",
    exchanges: [
      { speaker: "Tu", it: "Mi scusi, l'autobus va alla stazione?", en: "Excuse me, does this bus go to the train station?" },
      { speaker: "Amico", it: "Si', va li' direttamente, ci vado anch'io.", en: "Yes, it goes there directly. I am going there too." },
      { speaker: "Tu", it: "Sono dieci minuti che aspetto.", en: "When does it arrive? I have been waiting ten minutes." },
      { speaker: "Amico", it: "Dovrebbe arrivare presto. Sono venuto qui alle otto ed era in tempo.", en: "It should arrive soon. I came here at eight and it was on time." },
      { speaker: "Tu", it: "Devo partire prima di mezzogiorno, il treno parte alle dodici e mezza.", en: "I need to leave before noon. My train departs at half past twelve." },
      { speaker: "Amico", it: "Non preoccuparti, arriverai con il tempo da perdere.", en: "Do not worry. You will arrive with time to spare." },
      { speaker: "Tu", it: "Grazie, torno a casa dopo tre settimane.", en: "Thank you. I am returning home after three weeks here." },
      { speaker: "Amico", it: "Spero che tornerai presto, questa citta' e' bellissima.", en: "Really? I hope you come back soon. This city is beautiful." },
      { speaker: "Tu", it: "Tornero' la prossima estate, amo l'Italia.", en: "I will come back next summer. I love Italy." },
      { speaker: "Amico", it: "Ecco che arriva l'autobus!", en: "Here comes the bus now! Let us get on." },
    ]
  },
  "panchina-piazza_a2": {
    zoneId: "panchina-piazza",
    zoneName: "Park Bench",
    level: "a2",
    exchanges: [
      { speaker: "Tu", it: "Che ne dici di questo libro?", en: "What do you say about this book? I think it is very good." },
      { speaker: "Amico", it: "Parlo solo un po' di libri, ma vedo che ti piace.", en: "I speak only a little about books. But I see that you like it." },
      { speaker: "Tu", it: "Sì, lo scrittore sa raccontare una storia.", en: "Yes, the writer knows how to tell a story. Do you know him?" },
      { speaker: "Amico", it: "Conosco il nome, ma non ho letto i suoi libri.", en: "I know the name, but I have not read his books." },
      { speaker: "Tu", it: "Dovresti leggerle, capisco molte parole nuove grazie a lui.", en: "You should read them. I understand many new words thanks to him." },
      { speaker: "Amico", it: "Ho bisogno di leggere di più in italiano.", en: "I understand. I need to read more in Italian." },
      { speaker: "Tu", it: "Guarda, c'è l'autore ora! Sta camminando nel parco.", en: "Look, there is the author now! He is walking in the park." },
      { speaker: "Amico", it: "- Non lo vedo, oh si', ora lo vedo!", en: "Where? I do not see him. Oh yes, now I see!" },
      { speaker: "Tu", it: "E' molto famoso, tutti lo conoscono in questa citta'.", en: "He is very famous. Everyone knows him in this city." },
      { speaker: "Amico", it: "Vediamo di salutarlo se si avvicina.", en: "I see. Let us say hello if he comes closer." },
    ]
  },
  "settimana_a2": {
    zoneId: "settimana",
    zoneName: "The Week",
    level: "a2",
    exchanges: [
      { speaker: "Tu", it: "Diamo un'occhiata al calendario, che giorno è oggi?", en: "Let us look at the calendar. What day is it today?" },
      { speaker: "Amico", it: "Oggi e' mercoledi', a meta' settimana.", en: "Today is Wednesday. The middle of the week." },
      { speaker: "Tu", it: "Lunedì lavoro la mattina. Martedì studio l'italiano.", en: "On Monday I work in the morning. On Tuesday I study Italian." },
      { speaker: "Amico", it: "Giovedi' vado in palestra, venerdi' vedo i miei amici.", en: "On Thursday I go to the gym. On Friday I see my friends." },
      { speaker: "Tu", it: "Sabato e domenica sono i miei giorni preferiti. Riposo e dormo molto.", en: "Saturday and Sunday are my favourite days. I rest and sleep a lot." },
      { speaker: "Amico", it: "Preferisco venerdi', finisco il lavoro e mi sento libero.", en: "I prefer Friday. I finish work and I feel free." },
      { speaker: "Tu", it: "Lavori anche sabato, a volte?", en: "Do you also work on Saturday sometimes?" },
      { speaker: "Amico", it: "Mai di sabato, mi tengo sempre il sabato per la mia famiglia.", en: "Never on Saturday. I always keep Saturday for my family." },
      { speaker: "Tu", it: "Questa è una buona regola. Domenica mi piace camminare nel parco.", en: "That is a good rule. On Sunday I like to walk in the park." },
      { speaker: "Amico", it: "Anche io. La domenica è perfetta per lunghe passeggiate e buon cibo.", en: "Me too. Sunday is perfect for long walks and good food." },
    ]
  },
  "mesi_a2": {
    zoneId: "mesi",
    zoneName: "The Months",
    level: "a2",
    exchanges: [
      { speaker: "Tu", it: "In che mese sei nato?", en: "In what month were you born?" },
      { speaker: "Amico", it: "Sono nato a marzo.", en: "I was born in March. And you?" },
      { speaker: "Tu", it: "Sono nato a luglio, nel bel mezzo dell'estate.", en: "I was born in July, in the middle of summer." },
      { speaker: "Amico", it: "Mio fratello e' nato a gennaio, faceva molto freddo.", en: "My brother was born in January. It was very cold." },
      { speaker: "Tu", it: "I miei mesi preferiti sono maggio e settembre. Il tempo è bello.", en: "My favourite months are May and September. The weather is nice." },
      { speaker: "Amico", it: "Amo August perché vado sempre al mare.", en: "I love August because I always go to the sea." },
      { speaker: "Tu", it: "In ottobre e novembre le foglie diventano gialle e rosse.", en: "In October and November the leaves become yellow and red." },
      { speaker: "Amico", it: "Si', l'autunno e' bellissimo qui, ma non mi piace Dicembre, e' troppo buio.", en: "Yes, autumn is beautiful here. But I do not like December. It is too dark." },
      { speaker: "Tu", it: "Mi piace Dicembre a causa del Natale e delle luci.", en: "Really? I like December because of Christmas and the lights." },
      { speaker: "Amico", it: "Questo è vero. In febbraio c'è anche un bel carnevale in questa città.", en: "That is true. In February there is also a nice carnival in this city." },
    ]
  },
  "stagioni_a2": {
    zoneId: "stagioni",
    zoneName: "The Seasons",
    level: "a2",
    exchanges: [
      { speaker: "Tu", it: "Quale stagione ti piace di più?", en: "Which season do you like the most?" },
      { speaker: "Amico", it: "Mi piace la primavera, i fiori escono e i giorni si allungano.", en: "I like spring. The flowers come out and the days become longer." },
      { speaker: "Tu", it: "La primavera è bella, ma preferisco l'estate. Amo il sole e il caldo.", en: "Spring is nice, but I prefer summer. I love the sun and the heat." },
      { speaker: "Amico", it: "In estate vado in spiaggia ogni fine settimana. L'acqua è perfetta.", en: "In summer I go to the beach every weekend. The water is perfect." },
      { speaker: "Tu", it: "L'autunno è buono per leggere libri e bere tè caldo.", en: "Autumn is good for reading books and drinking hot tea." },
      { speaker: "Amico", it: "Sì, ma in autunno piove molto. Non mi piace la pioggia.", en: "Yes, but in autumn it rains a lot. I do not like rain." },
      { speaker: "Tu", it: "E l'inverno?", en: "What about winter? Do you ski?" },
      { speaker: "Amico", it: "Non scio, ma mi piace l'inverno per Natale e la neve in montagna.", en: "I do not ski, but I like winter for Christmas and the snow in the mountains." },
      { speaker: "Tu", it: "Ogni stagione ha qualcosa di bello. Voglio viaggiare in tutti e quattro.", en: "Every season has something beautiful. I want to travel in all four." },
      { speaker: "Amico", it: "E' un'idea meravigliosa, organizziamo un viaggio per la prossima primavera.", en: "That is a wonderful idea. Let us plan a trip for next spring." },
    ]
  },
  "avverbi-tempo_a2": {
    zoneId: "avverbi-tempo",
    zoneName: "Today & Tomorrow",
    level: "a2",
    exchanges: [
      { speaker: "Tu", it: "Credo di essere in ritardo.", en: "What time is it now? I think I am late." },
      { speaker: "Amico", it: "Sono le dieci, non sei in ritardo.", en: "It is ten o'clock now. You are not late." },
      { speaker: "Tu", it: "Oggi ho un sacco di lavoro, ieri ho riposato tutto il giorno.", en: "Good. Today I have a lot of work. Yesterday I rested all day." },
      { speaker: "Amico", it: "E domani?", en: "And tomorrow? Do you have plans?" },
      { speaker: "Tu", it: "Domani vado a trovare mia nonna, vado sempre a trovarla il venerdi'.", en: "Tomorrow I will visit my grandmother. I always visit her on Fridays." },
      { speaker: "Amico", it: "Non ho mai tempo per vedere la mia famiglia.", en: "That is sweet. I never have time to see my family." },
      { speaker: "Tu", it: "Dopo il lavoro, prima di cena, anche per cinque minuti.", en: "You should find time. After work, before dinner, even for five minutes." },
      { speaker: "Amico", it: "Hai ragione, poi chiamero' mia madre.", en: "You are right. Later I will call my mother." },
      { speaker: "Tu", it: "Non è mai troppo tardi per salutare.", en: "Do it now! It is never too late to say hello." },
      { speaker: "Amico", it: "Si', hai ragione, la chiamero' subito.", en: "Yes, you are right. I will call her right now." },
    ]
  },
};